//
// Generated by dtk
// Translation Unit: d_menu_item.cpp
//

#include "d/dolzel.h" // IWYU pragma: keep
#include "d/d_menu_item.h"
#include "JSystem/J2DGraph/J2DWindow.h"
#include "d/d_meter.h"
#include "m_Do/m_Do_controller_pad.h"

dMi_HIO_c g_miHIO;

/* 801C7B4C-801C7C7C       .text __ct__9dMi_HIO_cFv */
dMi_HIO_c::dMi_HIO_c() {
    field_0x08 = 0.8f;
    field_0x0C = 15;

    for (int i = 0; i < ARR_SIZE; i++) {
        arr_0x0E[i] = 0;
        arr_0x1A[i] = 10;
    }

    field_0x18 = 0;
    field_0x24 = 1;
    field_0x26 = -100;
    field_0x28 = -100;
    field_0x2A = -45;
    field_0x2C = 50;
    field_0x2E = 30;
    field_0x30 = -3;
    field_0x32 = 10;
    field_0x34 = 7;
    field_0x36 = 14;
    field_0x38 = 5;
    field_0x3A = 12;
    field_0x3C = 10;
    field_0x40 = 320;
    field_0x42 = 240;
    field_0x3E = 200;
    field_0x46 = 0;
    field_0x48 = 20;
    field_0x44 = -120;

    // Light Yellow-Green
    mClothColor.r = 0xE3;
    mClothColor.g = 0xFF;
    mClothColor.b = 0xB3;
    mClothColor.a = 0xDC;

    // Transparent
    mShadowColor.r = 0x00;
    mShadowColor.g = 0x00;
    mShadowColor.b = 0x00;
    mShadowColor.a = 0x00;

    field_0x5C = 130;

    mBlackColor.set(0x00, 0x00, 0x00, 0xFF); // Black
    // mWhiteColor stays as default.
}

/* 801C7C7C-801C7DC4       .text initialize__12dMenu_Item_cFv */
void dMenu_Item_c::initialize() {
    itemBitCheck(true);
    mTimer = 0;
    m858.mUserArea = 10;
    mA18[0].mUserArea = 0;
    m2422 = 0;
    noteInit();
    outFontInit();
    checkMove();
    itemNumberSet();
    m970.mInitAlpha = g_miHIO.field_0x5C;
    m23FA[0] = 0;
    m23FA[1] = 0;
    J2DWindow* window = (J2DWindow*)m14D0.pane;
    color_0x2320.r = window->mColorTL.r;
    color_0x2320.g = window->mColorTL.g;
    color_0x2320.b = window->mColorTL.b;
    color_0x2320.a = window->mColorTL.a;
    color_0x2324.r = window->mColorTR.r;
    color_0x2324.g = window->mColorTR.g;
    color_0x2324.b = window->mColorTR.b;
    color_0x2324.a = window->mColorTR.a;
    color_0x2328.r = window->mColorBL.r;
    color_0x2328.g = window->mColorBL.g;
    color_0x2328.b = window->mColorBL.b;
    color_0x2328.a = window->mColorBL.a;
    color_0x232C.r = window->mColorBR.r;
    color_0x232C.g = window->mColorBR.g;
    color_0x232C.b = window->mColorBR.b;
    color_0x232C.a = window->mColorBR.a;
    m2DPane->insertChild(m1460.pane, mA18[3].pane);
    m2DPane->insertChild(mA18[3].pane, mA18[2].pane);
    m2DPane->insertChild(mA18[2].pane, mA18[1].pane);
    m2DPane->insertChild(mA18[1].pane, mA18[0].pane);
}

/* 801C7DC4-801C8724       .text screenSet__12dMenu_Item_cFv */
void dMenu_Item_c::screenSet() {
    /* Nonmatching */
}

/* 801C8724-801C8B14       .text cursorAnime__12dMenu_Item_cFv */
void dMenu_Item_c::cursorAnime() {
    /* Nonmatching */
}

/* 801C8B14-801C8CA0       .text cursorMainMove__12dMenu_Item_cFv */
void dMenu_Item_c::cursorMainMove() {
    /* Nonmatching */
}

/* 801C8CA0-801C8E60       .text cursorSubMove__12dMenu_Item_cFv */
void dMenu_Item_c::cursorSubMove() {
    /* Nonmatching */
}

/* 801C8E60-801C9124       .text checkMove__12dMenu_Item_cFv */
void dMenu_Item_c::checkMove() {
    /* Nonmatching */
}

/* 801C9124-801C95FC       .text itemplaceCheck__12dMenu_Item_cFi */
void dMenu_Item_c::itemplaceCheck(int) {
    /* Nonmatching */
}

/* 801C95FC-801C9DF4       .text itemDecide__12dMenu_Item_cFv */
void dMenu_Item_c::itemDecide() {
    /* Nonmatching */
}

/* 801C9DF4-801CA18C       .text itemMove__12dMenu_Item_cFv */
void dMenu_Item_c::itemMove() {
    /* Nonmatching */
}

/* 801CA18C-801CA3F4       .text itemScale__12dMenu_Item_cFv */
void dMenu_Item_c::itemScale() {
    /* Nonmatching */
}

/* 801CA3F4-801CAA04       .text subWindowInit__12dMenu_Item_cFv */
void dMenu_Item_c::subWindowInit() {
    /* Nonmatching */
}

/* 801CAA04-801CAB48       .text subWindowDelete__12dMenu_Item_cFv */
void dMenu_Item_c::subWindowDelete() {
    (this->m858).mUserArea = 0;
    if (this->m2400[5] == 0) {
        this->mNowItem = fopMsgM_itemNum(dItemNo_SPOILS_BAG_e);
    } else if (this->m2400[5] == 1) {
        this->mNowItem = fopMsgM_itemNum(dItemNo_BAIT_BAG_e);
    } else {
        this->mNowItem = fopMsgM_itemNum(dItemNo_DELIVERY_BAG_e);
    }
    itemnameSet();
    itemScale();
    dMeter_subWinFlagOff();

    for (int i = 0; i < 8; i++) {
        fopMsgM_setNowAlphaZero(&mAF8[i]);
        fopMsgM_setNowAlphaZero(&mCB8[i]);
        fopMsgM_setNowAlphaZero(&mE78[i]);
        fopMsgM_setNowAlphaZero(&m1070[i]);
    }
    fopMsgM_setNowAlphaZero(&m1038);
    fopMsgM_setNowAlphaZero(&m1230);
    for (int i = 0; i < 9; i++) {
        fopMsgM_setNowAlphaZero(&m1268[i]);
    }
    fopMsgM_setNowAlphaZero(&this->m1460);
    this->m2DPane->insertChild(this->m1460.pane, this->mA18[3].pane);
    this->m2DPane->insertChild(this->mA18[3].pane, this->mA18[2].pane);
    this->m2DPane->insertChild(this->mA18[2].pane, this->mA18[1].pane);
    this->m2DPane->insertChild(this->mA18[1].pane, this->mA18[0].pane);
}

/* 801CAB48-801CB020       .text subItemDecide__12dMenu_Item_cFv */
void dMenu_Item_c::subItemDecide() {
    /* Nonmatching */
}

/* 801CB020-801CB168       .text itemnameMove__12dMenu_Item_cFv */
void dMenu_Item_c::itemnameMove() {
    /* Nonmatching */
}

/* 801CB168-801CB7C0       .text itemnameSet__12dMenu_Item_cFv */
void dMenu_Item_c::itemnameSet() {
    /* Nonmatching */
}

/* 801CB7C0-801CBEBC       .text itemnoteSet__12dMenu_Item_cFv */
void dMenu_Item_c::itemnoteSet() {
    /* Nonmatching */
}

/* 801CBEBC-801CBF44       .text outFontInit__12dMenu_Item_cFv */
void dMenu_Item_c::outFontInit() {
    J2DPane* piVar1;

    for (int i = 0; i < 15; i++) {
        this->m0B0[i].mUserArea = -1;
        piVar1 = m0B0[i].pane;
        piVar1->mRotation = 0.0f;
        piVar1->calcMtx();
        fopMsgM_setNowAlphaZero(&m0B0[i]);
    }
}

/* 801CBF44-801CC030       .text outFontMove__12dMenu_Item_cFv */
void dMenu_Item_c::outFontMove() {
    for (int i = 0; i < 15; i++) {
        if (this->m0B0[i].mUserArea != -1) {
            m3F8[i].mPosTopLeft.x = m0B0[i].mPosTopLeft.x + (m778.mPosTopLeft.x + (m820.mPosTopLeft.x + m7B0.mPosTopLeft.x));
            m3F8[i].mPosTopLeft.y = m0B0[i].mPosTopLeft.y + (m778.mPosTopLeft.y + (m820.mPosTopLeft.y + m7B0.mPosTopLeft.y));
            f32 y = m820.mPosCenter.y - m3F8[i].mPosTopLeft.y;
            m3F8[i].pane->rotate(m820.mPosCenter.x - m3F8[i].mPosTopLeft.x, y, ROTATE_Z, m820.pane->mRotation);
        } else {
            fopMsgM_setNowAlphaZero(&this->m0B0[i]);
        }
    }
}

/* 801CC030-801CC0F8       .text outFontDraw__12dMenu_Item_cFv */
void dMenu_Item_c::outFontDraw() {
    for (int i = 0; i < 15; i++) {
        if (this->m0B0[i].mUserArea != -1) {
            this->m0B0[i].mNowAlpha = (this->m778).pane->mAlpha;
            fopMsgM_outFontDraw2(
                (J2DPicture*)this->m0B0[i].pane,
                (J2DPicture*)this->m3F8[i].pane,
                this->m3F8[i].mPosTopLeft.x,
                this->m3F8[i].mPosTopLeft.y,
                g_msgHIO.field_0x70,
                g_msgHIO.field_0x70,
                &this->m0B0[i].mUserArea,
                this->m0B0[i].mNowAlpha,
                this->m0B0[i].mPosTopLeftOrig.y
            );
        } else {
            fopMsgM_setAlpha(&this->m0B0[i]);
        }
    }
}

/* 801CC0F8-801CC10C       .text noteCheck__12dMenu_Item_cFv */
u8 dMenu_Item_c::noteCheck() {
    return (this->m7E8).mUserArea == 1;
}

/* 801CC10C-801CC1AC       .text noteInit__12dMenu_Item_cFv */
void dMenu_Item_c::noteInit() {
    m7E8.mUserArea = 0;
    m7B0.mUserArea = 0;
    f32 half = 0.5f;
    m820.pane->rotate(m820.mSizeOrig.x * half, m820.mSizeOrig.y * half, ROTATE_Z, m820.mUserArea);
    fopMsgM_paneTrans(&m820, 0.0f, 0.0f);
}

/* 801CC1AC-801CC278       .text noteAppear__12dMenu_Item_cFv */
void dMenu_Item_c::noteAppear() {
    s16 sum = g_miHIO.field_0x38 + g_miHIO.field_0x3A;
    if (m7E8.mUserArea == 1) {
        if (m7B0.mUserArea <= sum) {
            noteOpen();
        } else if (m7B0.mUserArea > sum + 1) {
            noteClose();
        } else {
            u8 alpha = g_miHIO.field_0x5C;
            m970.mNowAlpha = alpha;
            m970.mInitAlpha = alpha;
            if (CPad_CHECK_TRIG_A(0) || CPad_CHECK_TRIG_B(0)) {
                m7B0.mUserArea = m7B0.mUserArea + 1;
                JAIZelBasic::zel_basic->seStart(0x816, (cXyz*)0x0, 0, 0, 1.0f, 1.0f, -1.0f, -1.0f, 0);
            }
        }
    }
}

/* 801CC278-801CC4F8       .text noteOpen__12dMenu_Item_cFv */
void dMenu_Item_c::noteOpen() {
    /* Nonmatching */
    f32 fVar1;
    f32 dVar11;

    int iVar9 = g_miHIO.field_0x30;
    int iVar10 = (s16)(g_miHIO.field_0x38 + g_miHIO.field_0x3A);
    f32 dx = (f32)g_miHIO.field_0x40 - (this->m820).mPosCenterOrig.x;
    f32 dy = (f32)g_miHIO.field_0x42 - (this->m820).mPosCenterOrig.y;
    fVar1 = 1.0f - fopMsgM_valueIncrease(iVar10, iVar10 - (this->m7B0).mUserArea, 0);
    if ((this->m7B0).mUserArea >= iVar10) {
        fopMsgM_setInitAlpha(&this->m970);
        fopMsgM_setInitAlpha(&this->m740);
        fopMsgM_setInitAlpha(&this->m778);
        JAIZelBasic::zel_basic->seStart(0x814, (cXyz*)0x0, 0, 0, 1.0f, 1.0f, -1.0f, -1.0f, 0);
    } else {
        fopMsgM_setNowAlpha(&this->m970, fVar1);
        fopMsgM_setNowAlpha(&this->m740, fVar1);
        fopMsgM_setNowAlpha(&this->m778, fVar1);
    }
    f32 half = 0.5f;
    this->m820.pane
        ->rotate((this->m820).mSize.x * half, (this->m820).mSize.y * half, ROTATE_Z, (this->m820).mUserArea + fVar1 * (iVar9 - (this->m820).mUserArea));
    iVar9 = (this->m7B0).mUserArea;
    if (iVar9 < g_miHIO.field_0x38) {
        fVar1 = (g_miHIO.field_0x08 * iVar9) / g_miHIO.field_0x38;
    } else {
        fVar1 = 1.0f - g_miHIO.field_0x08;
        dVar11 = fopMsgM_valueIncrease(g_miHIO.field_0x3A, iVar10 - iVar9, 0);
        dVar11 = fVar1 * (1.0f - dVar11);
        fVar1 = g_miHIO.field_0x08 + dVar11;
    }
    fopMsgM_paneTrans(&this->m820, dx * fVar1, dy * fVar1);
    (this->m7B0).mUserArea++;
}

/* 801CC4F8-801CC7D4       .text noteClose__12dMenu_Item_cFv */
void dMenu_Item_c::noteClose() {
    /* Nonmatching */
    s16 sVar3 = g_miHIO.field_0x30;
    s16 sVar7 = g_miHIO.field_0x44;
    int sum = (s16)(g_miHIO.field_0x38 + g_miHIO.field_0x3A);
    s16 sVar6 = g_miHIO.field_0x3C;
    f32 x = g_miHIO.field_0x40;
    f32 y = g_miHIO.field_0x42;
    f32 ddx = 2.0f * x - (this->m820).mPosCenterOrig.x - x;
    f32 ddy = 2.0f * y - (this->m820).mPosCenterOrig.y - y;
    f32 dx = x - (this->m820).mPosCenterOrig.x;
    f32 dy = y - (this->m820).mPosCenterOrig.y;
    f32 ratio = fopMsgM_valueIncrease(sVar6, (this->m7B0).mUserArea - (sum + 1), 0);
    fopMsgM_paneTrans(&this->m820, dx + ddx * ratio, dy + ddy * ratio);
    f32 half = 0.5f;
    this->m820.pane->rotate((this->m820).mSize.x * half, (this->m820).mSize.y * half, ROTATE_Z, sVar3 + ratio * (sVar7 - sVar3));
    (this->m7B0).mUserArea = (this->m7B0).mUserArea + 1;
    if ((this->m7B0).mUserArea > (s16)(sum + sVar6 + 1)) {
        fopMsgM_setInitAlpha(&this->m7B0);
        fopMsgM_setInitAlpha(&this->m7E8);
        fopMsgM_setInitAlpha(&this->m820);
        fopMsgM_setNowAlphaZero(&this->m970);
        fopMsgM_setNowAlphaZero(&this->m740);
        fopMsgM_setNowAlphaZero(&this->m778);
        (this->m7E8).mUserArea = 0;
        (this->m7B0).mUserArea = 0;
        this->m820.pane->rotate((this->m820).mSize.x * half, (this->m820).mSize.y * half, ROTATE_Z, (this->m820).mUserArea);
        fopMsgM_paneTrans(&this->m820, 0.0f, 0.0f);
    } else {
        fopMsgM_setNowAlpha(&this->m7B0, ratio = 1.0f - ratio);
        fopMsgM_setNowAlpha(&this->m7E8, ratio);
        fopMsgM_setNowAlpha(&this->m820, ratio);
        fopMsgM_setNowAlpha(&this->m970, ratio);
        fopMsgM_setNowAlpha(&this->m740, ratio);
        fopMsgM_setNowAlpha(&this->m778, ratio);
    }
}

/* 801CC7D4-801CC9D8       .text mainTrans__12dMenu_Item_cFff */
void dMenu_Item_c::mainTrans(float x, float y) {
    fopMsgM_paneTrans(&m1498, x, y);
    fopMsgM_paneTrans(&m14D0, x, y);
    fopMsgM_paneTrans(&m1508, x, y);
    fopMsgM_paneTrans(&m1540, x, y);
    fopMsgM_paneTrans(&m1578, x, y);
    fopMsgM_paneTrans(&m15B0, x, y);
    fopMsgM_paneTrans(&m15E8, x, y);
    fopMsgM_paneTrans(&m1620, x, y);
    for (int i = 0; i < 21; i++) {
        fopMsgM_paneTrans(&m1658[i], x, y);
        fopMsgM_paneTrans(&m1AF0[i], x, y);
    }
    for (int i = 0; i < 3; i++) {
        fopMsgM_paneTrans(&(&m1F88)[i], x, y);
    }
    for (int i = 0; i < 6; i++) {
        fopMsgM_paneTrans(&m20D8[i], x, y);
    }
    fopMsgM_paneTrans(&m2228, x, y);
    fopMsgM_paneTrans(&m2260, x, y);
    fopMsgM_paneTrans(&m2298, x, y);
    fopMsgM_paneTrans(&m22D0, x, y);
    for (int i = 0; i < 4; i++) {
        fopMsgM_paneTrans(&mA18[i], x, y);
    }
    for (int i = 0; i < 3; i++) {
        if (dComIfGp_getSelectItem(i) != 0xFF) {
            fopMsgM_paneTrans(&(&m2030)[i], x, y);
        }
    }
}

/* 801CC9D8-801CC9FC       .text titleTrans__12dMenu_Item_cFff */
void dMenu_Item_c::titleTrans(float, float) {
    /* Nonmatching */
}

/* 801CC9FC-801CCA88       .text noteRotate__12dMenu_Item_cFff */
void dMenu_Item_c::noteRotate(float, float) {
    /* Nonmatching */
}

/* 801CCA88-801CCB3C       .text nameTrans__12dMenu_Item_cFff */
void dMenu_Item_c::nameTrans(float, float) {
    /* Nonmatching */
}

/* 801CCB3C-801CCD74       .text mainOpenProc__12dMenu_Item_cFsss */
void dMenu_Item_c::mainOpenProc(short, short, short) {
    /* Nonmatching */
}

/* 801CCD74-801CCE5C       .text titleOpenProc__12dMenu_Item_cFss */
void dMenu_Item_c::titleOpenProc(short, short) {
    /* Nonmatching */
}

/* 801CCE5C-801CCF50       .text noteOpenProc__12dMenu_Item_cFss */
void dMenu_Item_c::noteOpenProc(short, short) {
    /* Nonmatching */
}

/* 801CCF50-801CD004       .text nameOpenProc__12dMenu_Item_cFss */
void dMenu_Item_c::nameOpenProc(short, short) {
    /* Nonmatching */
}

/* 801CD004-801CD04C       .text numberSet__12dMenu_Item_cFP7J2DPaneUc */
void dMenu_Item_c::numberSet(J2DPane*, unsigned char) {
    /* Nonmatching */
}

/* 801CD04C-801CD194       .text numberColor__12dMenu_Item_cFP7J2DPaneUc */
void dMenu_Item_c::numberColor(J2DPane*, unsigned char) {
    /* Nonmatching */
}

/* 801CD194-801CD3FC       .text itemNumberSet__12dMenu_Item_cFv */
void dMenu_Item_c::itemNumberSet() {
    /* Nonmatching */
}

/* 801CD3FC-801CDA14       .text itemCheck__12dMenu_Item_cFi */
void dMenu_Item_c::itemCheck(int) {
    /* Nonmatching */
}

/* 801CDA14-801CDB14       .text itemBitCheck__12dMenu_Item_cFb */
void dMenu_Item_c::itemBitCheck(bool) {
    /* Nonmatching */
}

/* 801CDB14-801CDC34       .text arrowLightAnime__12dMenu_Item_cFv */
void dMenu_Item_c::arrowLightAnime() {
    /* Nonmatching */
}

/* 801CDC34-801CDCF0       .text bottleFwaterCheck__12dMenu_Item_cFv */
void dMenu_Item_c::bottleFwaterCheck() {
    /* Nonmatching */
}

/* 801CDCF0-801CDDC0       .text recollectBossCheck__12dMenu_Item_cFv */
void dMenu_Item_c::recollectBossCheck() {
    /* Nonmatching */
}

/* 801CDDC0-801CF08C       .text cornerMove__12dMenu_Item_cFv */
void dMenu_Item_c::cornerMove() {
    /* Nonmatching */
}

/* 801CF08C-801CF12C       .text equipBeastItem__12dMenu_Item_cFi */
void dMenu_Item_c::equipBeastItem(int) {
    /* Nonmatching */
}

/* 801CF12C-801CF510       .text _create__12dMenu_Item_cFv */
void dMenu_Item_c::_create() {
    /* Nonmatching */

    g_miHIO.mNo = mDoHIO_createChild("アイテム画面", &g_miHIO); // "Item Screen"
}

/* 801CF510-801CF618       .text _delete__12dMenu_Item_cFv */
void dMenu_Item_c::_delete() {
    /* Nonmatching */
}

/* 801CF618-801D0524       .text _move__12dMenu_Item_cFv */
void dMenu_Item_c::_move() {
    /* Nonmatching */
}

/* 801D0524-801D0F50       .text _draw__12dMenu_Item_cFv */
void dMenu_Item_c::_draw() {
    /* Nonmatching */
}

/* 801D0F50-801D1438       .text _open__12dMenu_Item_cFv */
bool dMenu_Item_c::_open() {
    /* Nonmatching */
}

/* 801D1438-801D1CD4       .text _close__12dMenu_Item_cFv */
bool dMenu_Item_c::_close() {
    /* Nonmatching */
}

/* 801D1CD4-801D21A0       .text _open2__12dMenu_Item_cFv */
bool dMenu_Item_c::_open2() {
    /* Nonmatching */
    return false;
}

/* 801D21A0-801D2A4C       .text _close2__12dMenu_Item_cFv */
bool dMenu_Item_c::_close2() {
    /* Nonmatching */
    return false;
}
