//
// Generated by dtk
// Translation Unit: d_menu_item.cpp
//

#include "d/dolzel.h" // IWYU pragma: keep
#include "d/d_menu_item.h"
#include "JSystem/J2DGraph/J2DOrthoGraph.h"
#include "JSystem/J2DGraph/J2DTextBox.h"
#include "JSystem/J2DGraph/J2DWindow.h"
#include "d/d_2dnumber.h"
#include "d/d_lib.h"
#include "d/d_menu_save.h"
#include "d/d_meter.h"
#include "m_Do/m_Do_controller_pad.h"

dMi_HIO_c g_miHIO;

/* 801C7B4C-801C7C7C       .text __ct__9dMi_HIO_cFv */
dMi_HIO_c::dMi_HIO_c() {
    mNoteOpenRatio = 0.8f;
    field_0x0C = 15;

    for (int i = 0; i < ARR_SIZE; i++) {
        arr_0x0E[i] = 0;
        arr_0x1A[i] = 10;
    }

    field_0x18 = 0;
    field_0x24 = 1;
    mMainSlideX = -100;
    mTitleSlideY = -100;
    mNoteOpenAngle = -45;
    mNameSlideY = 50;
    field_0x2E = 30;
    mNoteOpenFinalAngle = -3;
    mCursorBlinkPeriod = 10;
    mCursorOffset1 = 7;
    mCursorOffset2 = 14;
    mNoteOpenDuration = 5;
    mNoteHoldDuration = 12;
    mNoteCloseDuration = 10;
    mScreenCenterX = 320;
    mScreenCenterY = 240;
    mNoteSlideY = 200;
    field_0x46 = 0;
    field_0x48 = 20;
    mNoteCloseAngle = -120;

    // Light Yellow-Green
    mClothColor.r = 0xE3;
    mClothColor.g = 0xFF;
    mClothColor.b = 0xB3;
    mClothColor.a = 0xDC;

    // Transparent
    mShadowColor.r = 0x00;
    mShadowColor.g = 0x00;
    mShadowColor.b = 0x00;
    mShadowColor.a = 0x00;

    mMaskAlpha = 130;

    mBlackColor.set(0x00, 0x00, 0x00, 0xFF); // Black
    // mWhiteColor stays as default.
}

/* 801C7C7C-801C7DC4       .text initialize__12dMenu_Item_cFv */
void dMenu_Item_c::initialize() {
    itemBitCheck(true);
    mTimer = 0;
    mItemNamePane.mUserArea = 10;
    mCursorPane[0].mUserArea = 0;
    m2422 = 0;
    noteInit();
    outFontInit();
    checkMove();
    itemNumberSet();
    m970.mInitAlpha = g_miHIO.mMaskAlpha;
    mCornerAnimTimer[0] = 0;
    mCornerAnimTimer[1] = 0;
    J2DWindow* window = (J2DWindow*)m14D0.pane;
    mCornerColorTL.r = window->mColorTL.r;
    mCornerColorTL.g = window->mColorTL.g;
    mCornerColorTL.b = window->mColorTL.b;
    mCornerColorTL.a = window->mColorTL.a;
    mCornerColorTR.r = window->mColorTR.r;
    mCornerColorTR.g = window->mColorTR.g;
    mCornerColorTR.b = window->mColorTR.b;
    mCornerColorTR.a = window->mColorTR.a;
    mCornerColorBL.r = window->mColorBL.r;
    mCornerColorBL.g = window->mColorBL.g;
    mCornerColorBL.b = window->mColorBL.b;
    mCornerColorBL.a = window->mColorBL.a;
    mCornerColorBR.r = window->mColorBR.r;
    mCornerColorBR.g = window->mColorBR.g;
    mCornerColorBR.b = window->mColorBR.b;
    mCornerColorBR.a = window->mColorBR.a;
    m2DPane->insertChild(m1460.pane, mCursorPane[3].pane);
    m2DPane->insertChild(mCursorPane[3].pane, mCursorPane[2].pane);
    m2DPane->insertChild(mCursorPane[2].pane, mCursorPane[1].pane);
    m2DPane->insertChild(mCursorPane[1].pane, mCursorPane[0].pane);
}

/* 801C7DC4-801C8724       .text screenSet__12dMenu_Item_cFv */
void dMenu_Item_c::screenSet() {
    static const u32 l_ft[15] = {
        'ft00',
        'ft01',
        'ft02',
        'ft03',
        'ft04',
        'ft05',
        'ft06',
        'ft07',
        'ft08',
        'ft09',
        'ft10',
        'ft11',
        'ft12',
        'ft13',
        'ft14',
    };
    static const u32 l_no[6] = {
        'no23',
        'no13',
        'no22',
        'no12',
        'no21',
        'no11',
    };
    static const u32 l_car[4] = {
        'car1',
        'car2',
        'car3',
        'car4',
    };
    static const u32 l_sin_01[8] = {
        '2401',
        '2501',
        '2801',
        '2601',
        '2701',
        '2901',
        '3001',
        '3101',
    };
    static const u32 l_sin_10[8] = {
        '2410',
        '2510',
        '2810',
        '2610',
        '2710',
        '2910',
        '3010',
        '3110',
    };
    static const u32 l_sit[9] = {
        'it21',
        'it22',
        'it25',
        'it23',
        'it24',
        'it26',
        'it27',
        'it28',
        'it29',
    };
    static const u32 l_sik[9] = {
        'ik21',
        'ik22',
        'ik25',
        'ik23',
        'ik24',
        'ik26',
        'ik27',
        'ik28',
        'ik29',
    };
    static const u32 l_sb[9] = {
        'sb00',
        'sb01',
        'sb02',
        'sb03',
        'sb04',
        'sb05',
        'sb06',
        'sb07',
        'sb08',
    };
    static const u32 l_it[21] = {
        'it00', 'it01', 'it02', 'it03', 'it04', 'it05', 'it06', 'it07', 'it08', 'it09', 'it10',
        'it11', 'it12', 'it13', 'it14', 'it15', 'it16', 'it17', 'it18', 'it19', 'it20',
    };
    static const u32 l_ik[21] = {
        'ik00', 'ik01', 'ik02', 'ik03', 'ik04', 'ik05', 'ik06', 'ik07', 'ik08', 'ik09', 'ik10',
        'ik11', 'ik12', 'ik13', 'ik14', 'ik15', 'ik16', 'ik17', 'ik18', 'ik19', 'ik20',
    };
    static const u32 l_ip[6] = {
        'ip01',
        'ip03',
        'ip05',
        'ip07',
        'ip09',
        'ip11',
    };
    static const u32 l_fd[15] = {
        'fd00',
        'fd01',
        'fd02',
        'fd03',
        'fd04',
        'fd05',
        'fd06',
        'fd07',
        'fd08',
        'fd09',
        'fd10',
        'fd11',
        'fd12',
        'fd13',
        'fd14',
    };

    J2DPane* root_pane;
    J2DPane* found_pane;

    root_pane = this->scrn->search('ROOT');
    this->m2DPane = root_pane;
    fopMsgM_setPaneData(&this->m008, this->scrn, 'ft15');
    fopMsgM_setPaneData(&this->m040, this->scrn, 'ft16');
    fopMsgM_setPaneData(&this->m078, this->scrn, 'ft17');
    for (int i = 0; i < 15; i++) {
        found_pane = this->scrn->search(l_ft[i]);
        fopMsgM_setPaneData(&this->m0B0[i], found_pane);
        found_pane = this->scrn->search(l_fd[i]);
        fopMsgM_setPaneData(&this->m3F8[i], found_pane);
        this->m0B0[i].mUserArea = -1;
    }
    fopMsgM_setPaneData(&this->m740, this->scrn, 'str0');
    fopMsgM_setPaneData(&this->m778, this->scrn, 'st00');
    if (g_dComIfG_gameInfo.save.getSavedata().getPlayer().getConfig().getRuby() != 0) {
        fopMsgM_paneTrans(&this->m778, 0.0, -4.0);
    }
    fopMsgM_setPaneData(&this->m7B0, this->scrn, 'nt00');
    fopMsgM_setPaneData(&this->m7E8, this->scrn, 'nk00');
    fopMsgM_setPaneData(&this->m820, this->scrn, 'no11');
    (this->m820).mUserArea = this->m820.pane->mRotation;
    ((J2DTextBox*)this->m740.pane)->setFont(this->mRFont);
    ((J2DTextBox*)this->m778.pane)->setFont(this->mFont);

    ((J2DTextBox*)m740.pane)->setWhite(0xFFFFFFFF);
    ((J2DTextBox*)m740.pane)->setCharColor(0x000000FF);
    ((J2DTextBox*)m740.pane)->setGradColor(0x000000FF);
    ((J2DTextBox*)m778.pane)->setWhite(0xFFFFFFFF);
    ((J2DTextBox*)m778.pane)->setCharColor(0x000000FF);
    ((J2DTextBox*)m778.pane)->setGradColor(0x000000FF);

    fopMsgM_setPaneData(&this->mItemNamePane, this->scrn, 'wd');
    (this->mItemNamePane).pane->show();
    ((J2DTextBox*)this->mItemNamePane.pane)->setFont(this->mFont);
    this->outFont->setPane(this->mFont, &this->mItemNamePane, &this->m008, &this->m040, &this->m078);
    fopMsgM_setPaneData(&this->m890, this->scrn, 'nm00');
    ((J2DTextBox*)this->m890.pane)->setFont(this->mFont);
    fopMsgM_setPaneData(&this->m8C8, this->scrn, 'nm01');
    ((J2DTextBox*)this->m8C8.pane)->setFont(this->mFont);
    fopMsgM_setPaneData(&this->m900, this->scrn, 'itnm');
    fopMsgM_setPaneData(&this->m938, this->scrn, 'itnk');
    fopMsgM_setPaneData(&this->m970, this->scrn, 'msk0');
    fopMsgM_setPaneData(&this->m9A8, this->scrn, 'tl00');
    fopMsgM_setPaneData(&this->m9E0, this->scrn, 'tk00');

    for (int i = 0; i < 4; i++) {
        fopMsgM_setPaneData(&this->mCursorPane[i], this->scrn, l_car[i]);
    }
    for (int i = 0; i < 8; i++) {
        fopMsgM_setPaneData(&this->mSubItemNumOnesPane[i], this->scrn, l_sin_01[i]);
        fopMsgM_setPaneData(&this->mSubItemNumTensPane[i], this->scrn, l_sin_10[i]);
        fopMsgM_setPaneData(&this->mSubItemPane[i], this->scrn, l_sit[i]);
        fopMsgM_setPaneData(&this->mSubItemShadowPane[i], this->scrn, l_sik[i]);
    }
    fopMsgM_setPaneData(&this->mSubItemBackPane, this->scrn, 'it29');
    fopMsgM_setPaneData(&this->mSubItemBackShadowPane, this->scrn, 'ik29');
    for (int i = 0; i < 9; i++) {
        fopMsgM_setPaneData(&this->m1268[i], this->scrn, l_sb[i]);
    }
    fopMsgM_setPaneData(&this->m1460, this->scrn, 'blak');
    fopMsgM_setPaneData(&this->mSaveIconPane, this->scrn, 'wdsv');
    fopMsgM_setPaneData(&this->m14D0, this->scrn, 'wk01');
    fopMsgM_setPaneData(&this->m1508, this->scrn, 'wk00');
    fopMsgM_setPaneData(&this->mPictureNumPane, this->scrn, '0301');
    fopMsgM_setPaneData(&this->mArrowNumOnesPane, this->scrn, '1301');
    fopMsgM_setPaneData(&this->mArrowNumTensPane, this->scrn, '1310');
    fopMsgM_setPaneData(&this->mBombNumOnesPane, this->scrn, '1401');
    fopMsgM_setPaneData(&this->mBombNumTensPane, this->scrn, '1410');
    for (int i = 0; i < 0x15; i++) {
        fopMsgM_setPaneData(&this->mItemPane[i], this->scrn, l_it[i]);
        fopMsgM_setPaneData(&this->mItemShadowPane[i], this->scrn, l_ik[i]);
    }
    fopMsgM_setPaneData(&this->mBowGlowPane[0], this->scrn, 'bwl1');
    fopMsgM_setPaneData(&this->mBowGlowPane[1], this->scrn, 'bwl2');
    fopMsgM_setPaneData(&this->mBowGlowPane[2], this->scrn, 'bwl3');
    this->mBowGlowPane[0].pane->hide();
    this->mBowGlowPane[1].pane->hide();
    this->mBowGlowPane[2].pane->hide();
    fopMsgM_setPaneData(&this->mCheckMarkPane[0], this->scrn, 'chk1');
    fopMsgM_setPaneData(&this->mCheckMarkPane[1], this->scrn, 'chk2');
    fopMsgM_setPaneData(&this->mCheckMarkPane[2], this->scrn, 'chk3');
    for (int i = 0; i < 6; i++) {
        fopMsgM_setPaneData(&this->mCategoryPane[i], this->scrn, l_ip[i]);
    }
    fopMsgM_setPaneData(&this->m2228, this->scrn, 'cc35');
    fopMsgM_setPaneData(&this->m2260, this->scrn, 'cc22');
    fopMsgM_setPaneData(&this->m2298, this->scrn, 'cc11');
    fopMsgM_setPaneData(&this->m22D0, this->scrn, 'cc00');
    for (int i = 0; i < 21; i++) {
        u8 itemNo = dComIfGs_getItem(i);
        if (itemNo != dItemNo_NONE_e) {
            if (itemNo == dItemNo_MAGIC_ARROW_e) {
                this->mBowGlowPane[0].pane->show();
                this->mBowGlowPane[1].pane->show();
                this->mBowGlowPane[2].pane->hide();
                itemNo = dItemNo_BOW_e;
            } else if (itemNo == dItemNo_LIGHT_ARROW_e) {
                this->mBowGlowPane[0].pane->show();
                this->mBowGlowPane[1].pane->show();
                this->mBowGlowPane[2].pane->show();
                itemNo = dItemNo_BOW_e;
            }
            JKRReadTypeResource(mItemTexBuffer[i], 0xc00, 'TIMG', dItem_data::getTexture(itemNo), dComIfGp_getItemIconArchive());
#if VERSION <= VERSION_JPN
            DCFlushRangeNoSync(mItemTexBuffer[i], 0xc00);

#else
            DCStoreRangeNoSync(mItemTexBuffer[i], 0xc00);

#endif

            ((J2DPicture*)mItemPane[i].pane)->changeTexture((ResTIMG*)mItemTexBuffer[i], 0);
            ((J2DPicture*)mItemShadowPane[i].pane)->changeTexture((ResTIMG*)mItemTexBuffer[i], 0);
        }
    }
    for (int i = 0; i < 8; i++) {
        if (dComIfGs_getItemBeast((u8)i) != dItemNo_NONE_e) {
            JKRReadTypeResource(mSubItemTexBuffer[i], 0xc00, 'TIMG', dItem_data::getTexture(dComIfGs_getItemBeast(i)), dComIfGp_getItemIconArchive());
#if VERSION <= VERSION_JPN
            DCFlushRangeNoSync(mSubItemTexBuffer[i], 0xc00);

#else
            DCStoreRangeNoSync(mSubItemTexBuffer[i], 0xc00);

#endif

            ((J2DPicture*)mSubItemPane[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
            ((J2DPicture*)mSubItemShadowPane[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
        }
    }
    JKRReadTypeResource(mSubItemTexBuffer[8], 0xc00, 'TIMG', "cover_return.bti", dComIfGp_getItemIconArchive());
#if VERSION <= VERSION_JPN
    DCFlushRangeNoSync(mSubItemTexBuffer[8], 0xc00);

#else
    DCStoreRangeNoSync(mSubItemTexBuffer[8], 0xc00);

#endif
    ((J2DPicture*)(this->mSubItemBackPane).pane)->changeTexture((ResTIMG*)this->mSubItemTexBuffer[8], 0);
    ((J2DPicture*)(this->mSubItemBackShadowPane).pane)->changeTexture((ResTIMG*)this->mSubItemTexBuffer[8], 0);
}

/* 801C8724-801C8B14       .text cursorAnime__12dMenu_Item_cFv */
void dMenu_Item_c::cursorAnime() {
    u8 itemNo = mNowItem;
    f32 half;
    if (itemNo == 0x15) {
        f32 pos_center_temp = mSaveIconPane.mPosCenter.x;
        f32 size_temp = mSaveIconPane.mSize.x;
        half = 0.5f;
        mCursorPane[0].mPosCenterOrig.x = pos_center_temp - size_temp * half;
        mCursorPane[0].mPosCenterOrig.y = mSaveIconPane.mPosCenter.y + mSaveIconPane.mSize.y * half;
        mCursorPane[1].mPosCenterOrig.x = mSaveIconPane.mPosCenter.x + mSaveIconPane.mSize.x * half;
        mCursorPane[1].mPosCenterOrig.y = mSaveIconPane.mPosCenter.y + mSaveIconPane.mSize.y * half;
        mCursorPane[2].mPosCenterOrig.x = mSaveIconPane.mPosCenter.x - mSaveIconPane.mSize.x * half;
        mCursorPane[2].mPosCenterOrig.y = mSaveIconPane.mPosCenter.y - mSaveIconPane.mSize.y * half;
        mCursorPane[3].mPosCenterOrig.x = mSaveIconPane.mPosCenter.x + mSaveIconPane.mSize.x * half;
        mCursorPane[3].mPosCenterOrig.y = mSaveIconPane.mPosCenter.y - mSaveIconPane.mSize.y * half;
    } else if (itemNo >= 0x18) {
        u8 idx;
        if (itemNo == 0xff) {
            idx = 8;
        } else {
            idx = itemNo - mItemState[0];
        }
        for (int i = 0; i < 4; i++) {
            mCursorPane[i].mPosCenterOrig.x = mSubItemPane[idx].mPosCenter.x + mCursorOffsetX[i];
            mCursorPane[i].mPosCenterOrig.y = mSubItemPane[idx].mPosCenter.y + mCursorOffsetY[i];
        }
    } else {
        for (int i = 0; i < 4; i++) {
            mCursorPane[i].mPosCenterOrig.x = mItemPane[itemNo].mPosCenter.x + mCursorOffsetX[i];
            mCursorPane[i].mPosCenterOrig.y = mItemPane[itemNo].mPosCenter.y + mCursorOffsetY[i];
        }
    }
    s16 x, y;
    if (mCursorPane[0].mUserArea < g_miHIO.mCursorBlinkPeriod) {
        for (int i = 0; i < 4; i++) {
            J2DPicture* pic = (J2DPicture*)mCursorPane[i].pane;
            pic->setBlendColorRatio(1.0f, 0.0f, 1.0f, 1.0f);
            pic->setBlendAlphaRatio(1.0f, 0.0f, 1.0f, 1.0f);
        }
        x = g_miHIO.mCursorOffset1;
        y = g_miHIO.mCursorOffset1;
    } else if (mCursorPane[0].mUserArea < g_miHIO.mCursorBlinkPeriod * 2) {
        for (int i = 0; i < 4; i++) {
            J2DPicture* pic = (J2DPicture*)mCursorPane[i].pane;
            pic->setBlendColorRatio(0.0f, 1.0f, 1.0f, 1.0f);
            pic->setBlendAlphaRatio(0.0f, 1.0f, 1.0f, 1.0f);
        }
        x = g_miHIO.mCursorOffset2;
        y = g_miHIO.mCursorOffset2;
    }
    fopMsgM_paneTrans(&mCursorPane[0], -x, y);
    fopMsgM_paneTrans(&mCursorPane[1], x, y);
    fopMsgM_paneTrans(&mCursorPane[2], -x, -y);
    fopMsgM_paneTrans(&mCursorPane[3], x, -y);
    mCursorPane[0].mUserArea++;
    if (mCursorPane[0].mUserArea >= g_miHIO.mCursorBlinkPeriod * 2) {
        mCursorPane[0].mUserArea = 0;
    }
}

/* 801C8B14-801C8CA0       .text cursorMainMove__12dMenu_Item_cFv */
void dMenu_Item_c::cursorMainMove() {
    u8 old_item;
    u8 item_no;
    bool triggered;

    this->stick->checkTrigger();
    old_item = this->mNowItem;
    triggered = this->stick->checkRightTrigger();
    if (triggered != 0) {
        item_no = this->mNowItem;
        if (item_no != 0x15) {
            if (item_no % 7 == 6) {
                this->mNowItem = item_no - 6;
            } else {
                this->mNowItem = item_no + 1;
            }
        }
    } else {
        triggered = this->stick->checkLeftTrigger();
        if (triggered != 0) {
            item_no = this->mNowItem;
            if (item_no != 0x15) {
                if ((item_no % 7) == 0) {
                    this->mNowItem = item_no + 6;
                } else {
                    this->mNowItem = item_no - 1;
                }
            }
        }
    }
    triggered = this->stick->checkUpTrigger();
    if (triggered != '\0') {
        item_no = this->mNowItem;
        if (item_no == 0x15) {
            this->mNowItem = '\x0e';
        } else if (item_no > 6) {
            this->mNowItem = item_no - 7;
        }
    } else {
        triggered = this->stick->checkDownTrigger();
        if (triggered != '\0') {
            item_no = this->mNowItem;
            if (item_no < 0xe) {
                this->mNowItem = item_no + 7;
            } else if (item_no >= 0xe && item_no <= 0x14) {
                this->mNowItem = '\x15';
            }
        }
    }
    if (this->mNowItem != old_item) {
        (this->mItemNamePane).mUserArea = 0;
        itemnameSet();
        JAIZelBasic::zel_basic->seStart(0x80e, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
    }
}

/* 801C8CA0-801C8E60       .text cursorSubMove__12dMenu_Item_cFv */
void dMenu_Item_c::cursorSubMove() {
    s16 max = g_menuHIO.field_0x82;
    u8 idx;
    if (mNowItem == 0xff) {
        idx = 8;
    } else {
        idx = mNowItem - mItemState[0];
    }
    stick->checkTrigger();
    if (stick->checkRightTrigger()) {
        if (idx % 3 != 2 && idx <= max - 1) {
            idx += 1;
        }
    } else if (stick->checkLeftTrigger()) {
        if (idx % 3 != 0) {
            idx -= 1;
        }
    }
    if (stick->checkUpTrigger()) {
        if (idx >= 3) {
            idx -= 3;
        }
    } else if (stick->checkDownTrigger()) {
        if ((u8)(idx + 3) <= max) {
            idx += 3;
        }
    }
    if (idx != (u8)(mNowItem - mItemState[0])) {
        if (idx == 8) {
            if (mNowItem != 0xff) {
                mNowItem = 0xff;
                JAIZelBasic::zel_basic->seStart(0x80e, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
            }
        } else {
            mNowItem = idx + mItemState[0];
            JAIZelBasic::zel_basic->seStart(0x80e, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
        }
        mItemNamePane.mUserArea = 0;
        itemnameSet();
    }
}

/* 801C8E60-801C9124       .text checkMove__12dMenu_Item_cFv */
void dMenu_Item_c::checkMove() {
    u8 inventory_slot; 
    for (s32 i = 0; i < 3; i++) {
        inventory_slot = dComIfGs_getSelectItem(i);
        if (inventory_slot != dInvSlot_NONE_e) {
            mCheckMarkPane[i].pane->show();
            if (dMeter_subWinFlag()) {
                if (inventory_slot >= dInvSlot_ReserveFirst_e) {
                    if (mItemState[5] == 2) {
                        u8 idx = inventory_slot - dInvSlot_ReserveFirst_e;
                        mCheckMarkPane[i].mPosCenter.x = mSubItemPane[idx].mPosCenter.x;
                        mCheckMarkPane[i].mPosCenter.y = mSubItemPane[idx].mPosCenter.y;
                        m2DPane->insertChild(mSubItemBackShadowPane.pane, mCheckMarkPane[i].pane);
                    } else {
                        u8 n = fopMsgM_itemNum(dItemNo_DELIVERY_BAG_e);
                        mCheckMarkPane[i].mPosCenter.x = mItemPane[n].mPosCenterOrig.x;
                        mCheckMarkPane[i].mPosCenter.y = mItemPane[n].mPosCenterOrig.y;
                        m2DPane->insertChild(mItemShadowPane[0x14].pane, mCheckMarkPane[i].pane);
                    }
                } else if (inventory_slot >= dInvSlot_BaitFirst_e) {
                    if (mItemState[5] == 1) {
                        u8 idx = inventory_slot - dInvSlot_BaitFirst_e;
                        mCheckMarkPane[i].mPosCenter.x = mSubItemPane[idx].mPosCenter.x;
                        mCheckMarkPane[i].mPosCenter.y = mSubItemPane[idx].mPosCenter.y;
                        m2DPane->insertChild(mSubItemBackShadowPane.pane, mCheckMarkPane[i].pane);
                    } else {
                        u8 n = fopMsgM_itemNum(dItemNo_BAIT_BAG_e);
                        mCheckMarkPane[i].mPosCenter.x = mItemPane[n].mPosCenterOrig.x;
                        mCheckMarkPane[i].mPosCenter.y = mItemPane[n].mPosCenterOrig.y;
                        m2DPane->insertChild(mItemShadowPane[0x14].pane, mCheckMarkPane[i].pane);
                    }
                } else if (inventory_slot >= dInvSlot_BeastFirst_e) {
                    if (mItemState[5] == 0) {
                        u8 idx = inventory_slot - dInvSlot_BeastFirst_e;
                        mCheckMarkPane[i].mPosCenter.x = mSubItemPane[idx].mPosCenter.x;
                        mCheckMarkPane[i].mPosCenter.y = mSubItemPane[idx].mPosCenter.y;
                        m2DPane->insertChild(mSubItemBackShadowPane.pane, mCheckMarkPane[i].pane);
                    } else {
                        u8 n = fopMsgM_itemNum(dItemNo_SPOILS_BAG_e);
                        mCheckMarkPane[i].mPosCenter.x = mItemPane[n].mPosCenterOrig.x;
                        mCheckMarkPane[i].mPosCenter.y = mItemPane[n].mPosCenterOrig.y;
                        m2DPane->insertChild(mItemShadowPane[0x14].pane, mCheckMarkPane[i].pane);
                    }
                } else {
                    mCheckMarkPane[i].mPosCenter.x = mItemPane[inventory_slot].mPosCenterOrig.x;
                    mCheckMarkPane[i].mPosCenter.y = mItemPane[inventory_slot].mPosCenterOrig.y;
                    m2DPane->insertChild(mItemShadowPane[0x14].pane, mCheckMarkPane[i].pane);
                }
            } else {
                if (inventory_slot >= dInvSlot_ReserveFirst_e) {
                    inventory_slot = fopMsgM_itemNum(dItemNo_DELIVERY_BAG_e);
                } else if (inventory_slot >= dInvSlot_BaitFirst_e) {
                    inventory_slot = fopMsgM_itemNum(dItemNo_BAIT_BAG_e);
                } else if (inventory_slot >= dInvSlot_BeastFirst_e) {
                    inventory_slot = fopMsgM_itemNum(dItemNo_SPOILS_BAG_e);
                }
                mCheckMarkPane[i].mPosCenter.x = mItemPane[inventory_slot].mPosCenterOrig.x;
                mCheckMarkPane[i].mPosCenter.y = mItemPane[inventory_slot].mPosCenterOrig.y;
                m2DPane->insertChild(mItemShadowPane[0x14].pane, mCheckMarkPane[i].pane);
            }
            mCheckMarkPane[i].mPosCenterOrig.x = mCheckMarkPane[i].mPosCenter.x;
            mCheckMarkPane[i].mPosCenterOrig.y = mCheckMarkPane[i].mPosCenter.y;
            fopMsgM_cposMove(&mCheckMarkPane[i]);
        } else {
            mCheckMarkPane[i].pane->hide();
        }
    }
}

/* 801C9124-801C95FC       .text itemplaceCheck__12dMenu_Item_cFi */
bool dMenu_Item_c::itemplaceCheck(int i_no) {
    static const int event[4] = {0, 1, 2, 3};
    static const int attack[4] = {7, 8, 9, 10};
    static const int bottle[4] = {0xe, 0xf, 0x10, 0x11};
    static const int bag[3] = {4, 0xb, 0x12};
    static const int wepon1[3] = {5, 0xc, 0x13};
    static const int wepon2[3] = {6, 0xd, 0x14};

    switch (i_no) {
        case 0:
            for (int i = 0; i < 4; i++) {
                if (dComIfGs_getItem(event[i]) != dItemNo_NONE_e) {
                    return true;
                }
            }
            break;
        case 1:
            for (int i = 0; i < 4; i++) {
                if (dComIfGs_getItem(attack[i]) != dItemNo_NONE_e) {
                    return true;
                }
            }
            break;
        case 2:
            for (int i = 0; i < 4; i++) {
                if (dComIfGs_getItem(bottle[i]) != dItemNo_NONE_e) {
                    return true;
                }
            }
            break;
        case 3:
            for (int i = 0; i < 3; i++) {
                if (dComIfGs_getItem(bag[i]) != dItemNo_NONE_e) {
                    return true;
                }
            }
            break;
        case 4:
            for (int i = 0; i < 3; i++) {
                if (dComIfGs_getItem(wepon1[i]) != dItemNo_NONE_e) {
                    return true;
                }
            }
            break;
        case 5:
            for (int i = 0; i < 3; i++) {
                if (dComIfGs_getItem(wepon2[i]) != dItemNo_NONE_e) {
                    return true;
                }
            }
            break;
    }
    return false;
}

/* 801C95FC-801C9DF4       .text itemDecide__12dMenu_Item_cFv */
void dMenu_Item_c::itemDecide() {
    if (mItemState[4] != dItemBtn_NONE_e) {
        dComIfGs_setSelectItem(mItemState[4], mItemState[1]);
        dComIfGp_setSelectItem(mItemState[4]);
        mItemState[4] = dItemBtn_NONE_e;
        if (mItemState[3] != dItemBtn_NONE_e) {
            dComIfGs_setSelectItem(mItemState[3], mItemState[2]);
            dComIfGp_setSelectItem(mItemState[3]);
            mItemState[3] = dItemBtn_NONE_e;
        }
        JAIZelBasic::zel_basic->seStart(0x817, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
    }
    if (CPad_CHECK_TRIG_X(0)) {
        mItemState[4] = dItemBtn_X_e;
    } else if (CPad_CHECK_TRIG_Y(0)) {
        mItemState[4] = dItemBtn_Y_e;
    } else if (CPad_CHECK_TRIG_Z(0)) {
        mItemState[4] = dItemBtn_Z_e;
    }
    if (dComIfGs_getItem(mNowItem) == dItemNo_SPOILS_BAG_e) {
        mItemState[5] = 0;
        subWindowInit();
        mItemState[4] = dItemBtn_NONE_e;
        mItemState[3] = dItemBtn_NONE_e;
        JAIZelBasic::zel_basic->seStart(0x84a, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
    } else if (dComIfGs_getItem(mNowItem) == dItemNo_BAIT_BAG_e) {
        mItemState[5] = 1;
        subWindowInit();
        mItemState[4] = dItemBtn_NONE_e;
        mItemState[3] = dItemBtn_NONE_e;
        JAIZelBasic::zel_basic->seStart(0x84a, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
    } else if (dComIfGs_getItem(mNowItem) == dItemNo_DELIVERY_BAG_e) {
        mItemState[5] = 2;
        subWindowInit();
        mItemState[4] = dItemBtn_NONE_e;
        mItemState[3] = dItemBtn_NONE_e;
        JAIZelBasic::zel_basic->seStart(0x84a, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
    } else {
        u8 first, second;
        if (mItemState[4] == dItemBtn_X_e) {
            first = dItemBtn_Y_e;
            second = dItemBtn_Z_e;
        }
        if (mItemState[4] == dItemBtn_Y_e) {
            first = dItemBtn_Z_e;
            second = dItemBtn_X_e;
        } else if (mItemState[4] == dItemBtn_Z_e) {
            first = dItemBtn_X_e;
            second = dItemBtn_Y_e;
        }
        if (mNowItem == dComIfGs_getSelectItem(first)) {
            mItemState[3] = first;
            mItemState[2] = dComIfGs_getSelectItem(mItemState[4]);
            if (dMeter_subWinFlag()) {
                subWindowDelete();
            }
        } else if (mNowItem == dComIfGs_getSelectItem(second)) {
            mItemState[3] = second;
            mItemState[2] = dComIfGs_getSelectItem(mItemState[4]);
            if (dMeter_subWinFlag()) {
                subWindowDelete();
            }
        }
        mItemState[1] = mNowItem;
        dMeter_itemMoveSet(&mItemPane[mItemState[1]], mItemState[4], mItemState[1]);
        JAIZelBasic::zel_basic->seStart(0x84a, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
    }
}

/* 801C9DF4-801CA18C       .text itemMove__12dMenu_Item_cFv */
void dMenu_Item_c::itemMove() {
    if (dMeter_itemMoveFlagCheck() == 2) {
        dComIfGs_setSelectItem(mItemState[4], mItemState[1]);
        dComIfGp_setSelectItem(mItemState[4]);
        mItemState[4] = dItemBtn_NONE_e;
        if (mItemState[3] != dItemBtn_NONE_e) {
            dComIfGs_setSelectItem(mItemState[3], mItemState[2]);
            dComIfGp_setSelectItem(mItemState[3]);
            mItemState[3] = dItemBtn_NONE_e;
        }
        JAIZelBasic::zel_basic->seStart(0x817, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
    }
}

/* 801CA18C-801CA3F4       .text itemScale__12dMenu_Item_cFv */
void dMenu_Item_c::itemScale() {
    int group;

    if (mNowItem == dItemNo_SMALL_KEY_e) {
        for (int i = 0; i < 0x15; i++) {
            fopMsgM_paneScaleXY(&mItemPane[i], 1.0f);
            fopMsgM_paneScaleXY(&mItemShadowPane[i], 1.0f);
        }
        for (int j = 0; j < 8; j++) {
            fopMsgM_paneScaleXY(&mSubItemPane[j], 1.0f);
            fopMsgM_paneScaleXY(&mSubItemShadowPane[j], 1.0f);
        }
        return;
    }

    u8 itemNo = mNowItem;
    if (itemNo >= 0x30) {
        group = dItemNo_DELIVERY_BAG_e;
    } else if (itemNo >= 0x24) {
        group = dItemNo_BAIT_BAG_e;
    } else if (itemNo >= 0x18) {
        group = dItemNo_SPOILS_BAG_e;
    } else {
        group = itemNo;
    }

    for (int i = 0; i < 0x15; i++) {
        if (i == group && mItemState[4] == 3) {
            fopMsgM_paneScaleXY(&mItemPane[i], g_menuHIO.field_0x8);
            fopMsgM_paneScaleXY(&mItemShadowPane[i], g_menuHIO.field_0x8);
            if (group == dInvSlot_BOW_e) {
                for (int k = 0; k < 3; k++) {
                    mBowGlowPane[k].mPosCenter.x =
                        mItemPane[i].mPosCenter.x + g_menuHIO.field_0x8 * (mBowGlowPane[k].mPosCenterOrig.x - mItemPane[i].mPosCenterOrig.x);
                    mBowGlowPane[k].mPosCenter.y =
                        mItemPane[i].mPosCenter.y + g_menuHIO.field_0x8 * (mBowGlowPane[k].mPosCenterOrig.y - mItemPane[i].mPosCenterOrig.y);
                }
            }
        } else {
            fopMsgM_paneScaleXY(&mItemPane[i], 1.0f);
            fopMsgM_paneScaleXY(&mItemShadowPane[i], 1.0f);
        }
    }

    if (mNowItem == 0xff) {
        for (int i = 0; i < 8; i++) {
            fopMsgM_paneScaleXY(&mSubItemPane[i], 1.0f);
            fopMsgM_paneScaleXY(&mSubItemShadowPane[i], 1.0f);
        }
    } else if (mNowItem >= 0x15) {
        group = mNowItem - mItemState[0];
        for (int i = 0; i < 8; i++) {
            if (i == group && mItemState[4] == 3) {
                fopMsgM_paneScaleXY(&mSubItemPane[i], g_menuHIO.field_0x8);
                fopMsgM_paneScaleXY(&mSubItemShadowPane[i], g_menuHIO.field_0x8);
            } else {
                fopMsgM_paneScaleXY(&mSubItemPane[i], 1.0f);
                fopMsgM_paneScaleXY(&mSubItemShadowPane[i], 1.0f);
            }
        }
    }
}

/* 801CA3F4-801CAA04       .text subWindowInit__12dMenu_Item_cFv */
void dMenu_Item_c::subWindowInit() {
    dMeter_subWinFlagOn();
    mItemNamePane.mUserArea = 0;
    if (mItemState[5] == 0) {
        mItemState[0] = 0x18;
        mNowItem = mItemState[0];
        for (int i = 0; i < 8; i++) {
            u8 slot = i;
            if (dComIfGs_getItemBeast(slot) != dItemNo_NONE_e) {
                mSubItemPane[i].mUserArea = 1;
                JKRReadTypeResource(mSubItemTexBuffer[i], 0xc00, 'TIMG', dItem_data::getTexture(dComIfGs_getItemBeast(slot)), dComIfGp_getItemIconArchive());
                DEMO_SELECT(DCFlushRangeNoSync, DCStoreRangeNoSync)(mSubItemTexBuffer[i], 0xc00);
                ((J2DPicture*)mSubItemPane[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
                ((J2DPicture*)mSubItemShadowPane[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
                mSubItemPane[i].pane->show();
                mSubItemShadowPane[i].pane->show();
                mSubItemNumTensPane[i].pane->show();
                mSubItemNumOnesPane[i].pane->show();
            } else {
                mSubItemPane[i].mUserArea = 0;
                mSubItemPane[i].pane->hide();
                mSubItemShadowPane[i].pane->hide();
                mSubItemNumTensPane[i].pane->hide();
                mSubItemNumOnesPane[i].pane->hide();
            }
            int idx = equipBeastItem(i);
            int count = dComIfGs_getBeastNum(idx);
            if (count == 0) {
                numberColor(mSubItemNumTensPane[i].pane, 2);
                numberColor(mSubItemNumOnesPane[i].pane, 2);
            } else if (count == 0x63) {
                numberColor(mSubItemNumTensPane[i].pane, 1);
                numberColor(mSubItemNumOnesPane[i].pane, 1);
            } else {
                numberColor(mSubItemNumTensPane[i].pane, 0);
                numberColor(mSubItemNumOnesPane[i].pane, 0);
            }
            if (count < 10) {
                mSubItemNumTensPane[i].pane->hide();
            } else {
                numberSet(mSubItemNumTensPane[i].pane, count / 10);
            }
            numberSet(mSubItemNumOnesPane[i].pane, count % 10);
        }
    } else if (mItemState[5] == 1) {
        mItemState[0] = 0x24;
        mNowItem = mItemState[0] + 3;
        for (int i = 0; i < 8; i++) {
            mSubItemNumTensPane[i].pane->hide();
            u8 slot = i;
            if (dComIfGs_getItemBait(slot) != 0xff) {
                mSubItemPane[i].mUserArea = 1;
                JKRReadTypeResource(mSubItemTexBuffer[i], 0xc00, 'TIMG', dItem_data::getTexture(dComIfGs_getItemBait(slot)), dComIfGp_getItemIconArchive());
                DEMO_SELECT(DCFlushRangeNoSync, DCStoreRangeNoSync)(mSubItemTexBuffer[i], 0xc00);
                ((J2DPicture*)mSubItemPane[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
                ((J2DPicture*)mSubItemShadowPane[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
                mSubItemPane[i].pane->show();
                mSubItemShadowPane[i].pane->show();
                if (dComIfGs_getItemBait(slot) == dItemNo_BIRD_BAIT_5_e) {
                    mSubItemNumOnesPane[i].pane->show();
                } else {
                    mSubItemNumOnesPane[i].pane->hide();
                }
            } else {
                mSubItemPane[i].mUserArea = 0;
                mSubItemPane[i].pane->hide();
                mSubItemShadowPane[i].pane->hide();
                mSubItemNumOnesPane[i].pane->hide();
            }
            int count = dComIfGs_getBaitNum(i);
            if (count == 0) {
                numberColor(mSubItemNumTensPane[i].pane, 2);
                numberColor(mSubItemNumOnesPane[i].pane, 2);
            } else if (count == 3) {
                numberColor(mSubItemNumTensPane[i].pane, 1);
                numberColor(mSubItemNumOnesPane[i].pane, 1);
            } else {
                numberColor(mSubItemNumTensPane[i].pane, 0);
                numberColor(mSubItemNumOnesPane[i].pane, 0);
            }
            numberSet(mSubItemNumOnesPane[i].pane, count % 10);
        }
    } else {
        mItemState[0] = 0x30;
        mNowItem = mItemState[0] + 6;
        for (int i = 0; i < 8; i++) {
            mSubItemNumTensPane[i].pane->hide();
            mSubItemNumOnesPane[i].pane->hide();
            u8 slot = i;
            if (dComIfGs_getItemReserve(slot) != 0xff) {
                mSubItemPane[i].mUserArea = 1;
                JKRReadTypeResource(mSubItemTexBuffer[i], 0xc00, 'TIMG', dItem_data::getTexture(dComIfGs_getItemReserve(slot)), dComIfGp_getItemIconArchive());
                DEMO_SELECT(DCFlushRangeNoSync, DCStoreRangeNoSync)(mSubItemTexBuffer[i], 0xc00);
                ((J2DPicture*)mSubItemPane[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
                ((J2DPicture*)mSubItemShadowPane[i].pane)->changeTexture((ResTIMG*)mSubItemTexBuffer[i], 0);
                mSubItemPane[i].pane->show();
                mSubItemShadowPane[i].pane->show();
            } else {
                mSubItemPane[i].mUserArea = 0;
                mSubItemPane[i].pane->hide();
                mSubItemShadowPane[i].pane->hide();
            }
        }
    }

    itemnameSet();

    for (int i = 0; i < 8; i++) {
        fopMsgM_paneScaleXY(&mSubItemPane[i], 1.0f);
        fopMsgM_paneScaleXY(&mSubItemShadowPane[i], 1.0f);
    }
    for (int i = 0; i < 8; i++) {
        fopMsgM_setInitAlpha(&mSubItemNumOnesPane[i]);
        fopMsgM_setInitAlpha(&mSubItemNumTensPane[i]);
        fopMsgM_setInitAlpha(&mSubItemPane[i]);
        fopMsgM_setInitAlpha(&mSubItemShadowPane[i]);
    }
    fopMsgM_setInitAlpha(&mSubItemBackPane);
    fopMsgM_setInitAlpha(&mSubItemBackShadowPane);
    for (int i = 0; i < 9; i++) {
        fopMsgM_setInitAlpha(&m1268[i]);
    }
    fopMsgM_setInitAlpha(&m1460);

    m2DPane->insertChild(mSubItemNumTensPane[7].pane, mCursorPane[3].pane);
    m2DPane->insertChild(mCursorPane[3].pane, mCursorPane[2].pane);
    m2DPane->insertChild(mCursorPane[2].pane, mCursorPane[1].pane);
    m2DPane->insertChild(mCursorPane[1].pane, mCursorPane[0].pane);
}

/* 801CAA04-801CAB48       .text subWindowDelete__12dMenu_Item_cFv */
void dMenu_Item_c::subWindowDelete() {
    (this->mItemNamePane).mUserArea = 0;
    if (this->mItemState[5] == 0) {
        this->mNowItem = fopMsgM_itemNum(dItemNo_SPOILS_BAG_e);
    } else if (this->mItemState[5] == 1) {
        this->mNowItem = fopMsgM_itemNum(dItemNo_BAIT_BAG_e);
    } else {
        this->mNowItem = fopMsgM_itemNum(dItemNo_DELIVERY_BAG_e);
    }
    itemnameSet();
    itemScale();
    dMeter_subWinFlagOff();

    for (int i = 0; i < 8; i++) {
        fopMsgM_setNowAlphaZero(&mSubItemNumOnesPane[i]);
        fopMsgM_setNowAlphaZero(&mSubItemNumTensPane[i]);
        fopMsgM_setNowAlphaZero(&mSubItemPane[i]);
        fopMsgM_setNowAlphaZero(&mSubItemShadowPane[i]);
    }
    fopMsgM_setNowAlphaZero(&mSubItemBackPane);
    fopMsgM_setNowAlphaZero(&mSubItemBackShadowPane);
    for (int i = 0; i < 9; i++) {
        fopMsgM_setNowAlphaZero(&m1268[i]);
    }
    fopMsgM_setNowAlphaZero(&this->m1460);
    this->m2DPane->insertChild(this->m1460.pane, this->mCursorPane[3].pane);
    this->m2DPane->insertChild(this->mCursorPane[3].pane, this->mCursorPane[2].pane);
    this->m2DPane->insertChild(this->mCursorPane[2].pane, this->mCursorPane[1].pane);
    this->m2DPane->insertChild(this->mCursorPane[1].pane, this->mCursorPane[0].pane);
}

/* 801CAB48-801CB020       .text subItemDecide__12dMenu_Item_cFv */
void dMenu_Item_c::subItemDecide() {
    if (mItemState[4] != dItemBtn_NONE_e) {
        dComIfGs_setSelectItem(mItemState[4], mItemState[1]);
        dComIfGp_setSelectItem(mItemState[4]);
        mItemState[4] = dItemBtn_NONE_e;
        if (mItemState[3] != dItemBtn_NONE_e) {
            dComIfGs_setSelectItem(mItemState[3], mItemState[2]);
            dComIfGp_setSelectItem(mItemState[3]);
            mItemState[3] = dItemBtn_NONE_e;
        }
        JAIZelBasic::zel_basic->seStart(0x817, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
    }
    if (CPad_CHECK_TRIG_X(0)) {
        mItemState[4] = dItemBtn_X_e;
    } else if (CPad_CHECK_TRIG_Y(0)) {
        mItemState[4] = dItemBtn_Y_e;
    } else if (CPad_CHECK_TRIG_Z(0)) {
        mItemState[4] = dItemBtn_Z_e;
    }
    u8 first, second;
    if (mItemState[4] == dItemBtn_X_e) {
        first = dItemBtn_Y_e;
        second = dItemBtn_Z_e;
    } else if (mItemState[4] == dItemBtn_Y_e) {
        first = dItemBtn_Z_e;
        second = dItemBtn_X_e;
    } else if (mItemState[4] == dItemBtn_Z_e) {
        first = dItemBtn_X_e;
        second = dItemBtn_Y_e;
    }
    if (mNowItem == dComIfGs_getSelectItem(first)) {
        mItemState[3] = first;
        mItemState[2] = dComIfGs_getSelectItem(mItemState[4]);
    } else if (mNowItem == dComIfGs_getSelectItem(second)) {
        mItemState[3] = second;
        mItemState[2] = dComIfGs_getSelectItem(mItemState[4]);
    }
    mItemState[1] = mNowItem;
    dMeter_itemMoveSet(&mSubItemPane[mItemState[1] - mItemState[0]], mItemState[4], mItemState[1]);
    JAIZelBasic::zel_basic->seStart(0x84a, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
    if (dMeter_subWinFlag()) {
        subWindowDelete();
    }
}

inline int sub(int i_value, int i_sub) {
    int ret = i_value - i_sub;
    return ret;
}

/* 801CB020-801CB168       .text itemnameMove__12dMenu_Item_cFv */
void dMenu_Item_c::itemnameMove() {
    mItemNamePane.mUserArea = mItemNamePane.mUserArea + 1;
    if (mItemNamePane.mUserArea > 0x82) {
        mItemNamePane.mUserArea = 0xb;
    }
    if (mItemNamePane.mUserArea <= 0xa) {
        f32 t = fopMsgM_valueIncrease(10, mItemNamePane.mUserArea, 0);
        fopMsgM_setNowAlpha(&m890, t);
        fopMsgM_setNowAlpha(&m8C8, 1.0f - t);
        fopMsgM_setNowAlphaZero(&mItemNamePane);
    } else if (mItemNamePane.mUserArea <= 0x3c) {
        fopMsgM_setInitAlpha(&m890);
        fopMsgM_setNowAlphaZero(&mItemNamePane);
    } else if (mItemNamePane.mUserArea <= 0x46) {
        f32 t = fopMsgM_valueIncrease(10, sub(mItemNamePane.mUserArea, 0x3c), 0);
        fopMsgM_setNowAlpha(&m890, 1.0f - t);
        fopMsgM_setNowAlpha(&mItemNamePane, t);
    } else if (mItemNamePane.mUserArea <= 0x78) {
        fopMsgM_setNowAlphaZero(&m890);
        fopMsgM_setInitAlpha(&mItemNamePane);
    } else if (mItemNamePane.mUserArea <= 0x82) {
        f32 t = fopMsgM_valueIncrease(10, sub(mItemNamePane.mUserArea, 0x78), 0);
        fopMsgM_setNowAlpha(&m890, t);
        fopMsgM_setNowAlpha(&mItemNamePane, 1.0f - t);
    }
    outFont->move();
}

/* 801CB168-801CB7C0       .text itemnameSet__12dMenu_Item_cFv */
void dMenu_Item_c::itemnameSet() {
    /* Nonmatching */
    fopMsgM_itemMsgGet_c msgGet;
    int i = 0;
    J2DTextBox::TFontSize size2;
    J2DTextBox::TFontSize size3;
    J2DTextBox::TFontSize size;

    size.mSizeY = 29.0f;
    size.mSizeX = 29.0f;
    ((J2DTextBox*)mItemNamePane.pane)->setFontSize(size);

    ((J2DTextBox*)m890.pane)->getFontSize(size2);
    ((J2DTextBox*)m8C8.pane)->setFontSize(size2);
    ((J2DTextBox*)m8C8.pane)->mCharSpace = ((J2DTextBox*)m890.pane)->mCharSpace;

    for (; name[0][i] != '\0'; i++) {
        name[1][i] = name[0][i];
    }
    name[1][i] = '\0';

    ((J2DTextBox*)m8C8.pane)->setString(name[1]);
    strcpy(name[0], "");

    u8 itemNo = mNowItem;
    u32 msgNo;
    if (itemNo == 0x15) {
        msgNo = 0x1f8;
    } else {
        if (dComIfGs_getItem(itemNo) != dItemNo_NONE_e) {
            u32 num = dItem_data::getItemMesgNum(dComIfGs_getItem(itemNo));
            msgNo = num;
            if (num == 0) {
                msgNo = 0x19c;
            }
        } else {
            return;
        }
    }

    {
        mesg_header* head_p = msgGet.getMesgHeader(msgNo);
        JUT_ASSERT(0x565, head_p);

        ((J2DTextBox*)m890.pane)->getFontSize(size3);
        size3.mSizeX = size3.mSizeY;

        const char* p;
        const char* msg = msgGet.getMessage(head_p);
        bool first = false;
        f32 scale = size3.mSizeY / (f32)mFont->getCellWidth();
        f32 total;
        p = msg;
        char buf[3];
        while (*p != '\0') {
            buf[2] = '\0';
            buf[1] = '\0';
            buf[0] = '\0';
            u8 byte = *(u8*)p;
            if (byte == 0x1a) {
                p += 1;
                p += (s8)*p - 1;
                continue;
            }
            int code;
            if ((byte >> 4) == 8 || (byte >> 4) == 9) {
                code = ((u8)p[0] << 8) | (u8)p[1];
                buf[0] = p[0];
                buf[1] = p[1];
                buf[2] = '\0';
                p += 2;
            } else {
                code = byte;
                buf[0] = byte;
                buf[1] = '\0';
                p += 1;
            }
            int width = mFont->getWidth(code);
            strcat(name[0], buf);
            if (!first) {
                total = scale * (f32)(width + mFont->getOffset(code));
                first = true;
            } else {
                total += (f32)width * scale;
            }
        }

        f32 boxWidth = m890.pane->mBounds.getWidth();
        if (boxWidth < total) {
            size3.mSizeX = (int)(size3.mSizeX * boxWidth / total);
        }
        ((J2DTextBox*)m890.pane)->setFontSize(size3);
        ((J2DTextBox*)m890.pane)->mCharSpace = 0.0f;
        ((J2DTextBox*)m890.pane)->setString(name[0]);

        if (mNowItem == 0x15) {
            outFont->messageSet(0x1fc);
        } else if (mNowItem == 4 || mNowItem == 0xb || mNowItem == 0x12) {
            outFont->messageSet(0x1f5);
        } else {
            outFont->messageSet(0x1f9);
        }
        outFont->setLeftUpPos(mItemNamePane.mPosTopLeft.x, mItemNamePane.mPosTopLeft.y);
    }
}

/* 801CB7C0-801CBEBC       .text itemnoteSet__12dMenu_Item_cFv */
void dMenu_Item_c::itemnoteSet() {
    fopMsgM_itemMsgGet_c msgGet;
    fopMsgM_msgDataProc_c msgDataProc;

    strcpy(note[0], "");
    strcpy(note[1], "");
    strcpy(dummy[0], "");
    strcpy(dummy[1], "");

    outFontInit();

    if (dComIfGs_getOptRuby()) {
        m740.pane->hide();
    } else {
        m740.pane->show();
    }

    f32 ruby_font_size = m740.pane[1].getGlbBounds().i.x;

    J2DTextBox::TFontSize size;
    size.mSizeX = g_msgHIO.field_0x70;
    size.mSizeY = g_msgHIO.field_0x70;
    ((J2DTextBox*)m778.pane)->setFontSize(size);
    ((J2DTextBox*)m778.pane)->setLineSpace(g_msgHIO.field_0x5e);

    u32 msgNo;
    if (dComIfGs_getItem(mNowItem) != dItemNo_NONE_e) {
        u32 num = dItem_data::getItemMesgNum(dComIfGs_getItem(mNowItem));
        if (num == 0) {
            msgNo = 0x264;
        } else {
            msgNo = num + 0xC8;
        }
    } else {
        return;
    }

    {
        mesg_header* head_p = msgGet.getMesgHeader(msgNo);
        JUT_ASSERT(0x5F1, head_p);

        const char* mesg = msgGet.getMessage(head_p);
        JMSMesgEntry_c msg_entry;
        msg_entry = msgGet.getMesgEntry(head_p);

        msgDataProc.dataInit();
        msgDataProc.bmgData = mesg;
        msgDataProc.setOutMessage(note[0], note[1], dummy[0], dummy[1]);
        msgDataProc.font[0] = mFont;
        msgDataProc.font[1] = mRFont;
        msgDataProc.charSpace = ((J2DTextBox*)m778.pane)->getCharSpace();
        msgDataProc.rubyCharSpace = ((J2DTextBox*)m740.pane)->getCharSpace();
        msgDataProc.lineSpace = ((J2DTextBox*)m778.pane)->getLineSpace();
        msgDataProc.mesgEntry = &msg_entry;
        msgDataProc.fontSize = size.mSizeX;
        msgDataProc.rubyFontSize = ruby_font_size;
        msgDataProc.lineWidth = 0x1FE;
        msgDataProc.centerLineWidth = 0x1E6;
        msgDataProc.sendSpeed = 2;
        msgDataProc.spaceTimer = 0;
        msgDataProc.field_0x299 = 1;
        msgDataProc.spaceFlag = 0;

        msgDataProc.stringLength();
        msgDataProc.stringShift();
        msgDataProc.iconIdxRefresh();

        s16 line_count = msgDataProc.lineCount;
        msgDataProc.lineCount = 0;
        f32 line_shift_y = (f32)(3 - line_count) * (((J2DTextBox*)m778.pane)->getLineSpace() / 2.0f);
        ((J2DTextBox*)m740.pane)->shiftSet(0.0f, line_shift_y);
        ((J2DTextBox*)m778.pane)->shiftSet(0.0f, line_shift_y);
        msgDataProc.stringSet();

        ((J2DTextBox*)m778.pane)->setString(note[0]);
        ((J2DTextBox*)m740.pane)->setString(note[1]);

        int half_line_space = ((J2DTextBox*)m778.pane)->getLineSpace() / 2.0f;
        for (int i = 0; i < 0xf; i++) {
            u32 r6 = msgDataProc.field_0x281[i];
            u32 color = msgDataProc.field_0x220[i];
            if (color == 0xFFFFFFFF) {
                color = 0xFF;
            }
            if (r6 == 0xFF) {
                continue;
            }
            if (m0B0[i].mUserArea != -1) {
                continue;
            }
            if (r6 == 0x16) {
                continue;
            }
            m0B0[i].mPosTopLeft.x = (f32)msgDataProc.field_0x168[i];
            m0B0[i].mPosTopLeft.y = (f32)(half_line_space * (3 - line_count + msgDataProc.field_0x1A4[i] * 2));
            m0B0[i].mPosTopLeftOrig.y = (f32)r6;

            fopMsgM_outFontSet((J2DPicture*)m0B0[i].pane, &m0B0[i].mUserArea, color, r6);
        }
    }
}

/* 801CBEBC-801CBF44       .text outFontInit__12dMenu_Item_cFv */
void dMenu_Item_c::outFontInit() {
    J2DPane* font_pane;

    for (int i = 0; i < 15; i++) {
        this->m0B0[i].mUserArea = -1;
        font_pane = m0B0[i].pane;
        font_pane->mRotation = 0.0f;
        font_pane->calcMtx();
        fopMsgM_setNowAlphaZero(&m0B0[i]);
    }
}

/* 801CBF44-801CC030       .text outFontMove__12dMenu_Item_cFv */
void dMenu_Item_c::outFontMove() {
    for (int i = 0; i < 15; i++) {
        if (this->m0B0[i].mUserArea != -1) {
            m3F8[i].mPosTopLeft.x = m0B0[i].mPosTopLeft.x + (m778.mPosTopLeft.x + (m820.mPosTopLeft.x + m7B0.mPosTopLeft.x));
            m3F8[i].mPosTopLeft.y = m0B0[i].mPosTopLeft.y + (m778.mPosTopLeft.y + (m820.mPosTopLeft.y + m7B0.mPosTopLeft.y));
            f32 x = m820.mPosCenter.x - m3F8[i].mPosTopLeft.x;
            f32 y = m820.mPosCenter.y - m3F8[i].mPosTopLeft.y;
            m3F8[i].pane->rotate(x, y, ROTATE_Z, m820.pane->mRotation);
        } else {
            fopMsgM_setNowAlphaZero(&this->m0B0[i]);
        }
    }
}

/* 801CC030-801CC0F8       .text outFontDraw__12dMenu_Item_cFv */
void dMenu_Item_c::outFontDraw() {
    for (int i = 0; i < 15; i++) {
        if (this->m0B0[i].mUserArea != -1) {
            this->m0B0[i].mNowAlpha = (this->m778).pane->mAlpha;
            fopMsgM_outFontDraw2(
                (J2DPicture*)this->m0B0[i].pane,
                (J2DPicture*)this->m3F8[i].pane,
                this->m3F8[i].mPosTopLeft.x,
                this->m3F8[i].mPosTopLeft.y,
                g_msgHIO.field_0x70,
                g_msgHIO.field_0x70,
                &this->m0B0[i].mUserArea,
                this->m0B0[i].mNowAlpha,
                this->m0B0[i].mPosTopLeftOrig.y
            );
        } else {
            fopMsgM_setAlpha(&this->m0B0[i]);
        }
    }
}

/* 801CC0F8-801CC10C       .text noteCheck__12dMenu_Item_cFv */
u8 dMenu_Item_c::noteCheck() {
    return (this->m7E8).mUserArea == 1;
}

/* 801CC10C-801CC1AC       .text noteInit__12dMenu_Item_cFv */
void dMenu_Item_c::noteInit() {
    m7E8.mUserArea = 0;
    m7B0.mUserArea = 0;
    f32 half = 0.5f;
    m820.pane->rotate(m820.mSizeOrig.x * half, m820.mSizeOrig.y * half, ROTATE_Z, m820.mUserArea);
    fopMsgM_paneTrans(&m820, 0.0f, 0.0f);
}

/* 801CC1AC-801CC278       .text noteAppear__12dMenu_Item_cFv */
void dMenu_Item_c::noteAppear() {
    s16 sum = g_miHIO.mNoteOpenDuration + g_miHIO.mNoteHoldDuration;
    if (m7E8.mUserArea == 1) {
        if (m7B0.mUserArea <= sum) {
            noteOpen();
        } else if (m7B0.mUserArea > sum + 1) {
            noteClose();
        } else {
            u8 alpha = g_miHIO.mMaskAlpha;
            m970.mNowAlpha = alpha;
            m970.mInitAlpha = alpha;
            if (CPad_CHECK_TRIG_A(0) || CPad_CHECK_TRIG_B(0)) {
                m7B0.mUserArea = m7B0.mUserArea + 1;
                JAIZelBasic::zel_basic->seStart(0x816, (cXyz*)0x0, 0, 0, 1.0f, 1.0f, -1.0f, -1.0f, 0);
            }
        }
    }
}

/* 801CC278-801CC4F8       .text noteOpen__12dMenu_Item_cFv */
void dMenu_Item_c::noteOpen() {
    f32 ratio;
    f32 tmp_ratio;

    s32 iVar9 = (int)g_miHIO.mNoteOpenFinalAngle;
    s16 open_total = (s16)(g_miHIO.mNoteOpenDuration + g_miHIO.mNoteHoldDuration);
    f32 dx = (f32)g_miHIO.mScreenCenterX - (this->m820).mPosCenterOrig.x;
    f32 dy = (f32)g_miHIO.mScreenCenterY - (this->m820).mPosCenterOrig.y;
    ratio = 1.0f - fopMsgM_valueIncrease(open_total, open_total - (this->m7B0).mUserArea, 0);
    if ((this->m7B0).mUserArea >= open_total) {
        fopMsgM_setInitAlpha(&this->m970);
        fopMsgM_setInitAlpha(&this->m740);
        fopMsgM_setInitAlpha(&this->m778);
        JAIZelBasic::zel_basic->seStart(0x814, (cXyz*)0x0, 0, 0, 1.0f, 1.0f, -1.0f, -1.0f, 0);
    } else {
        fopMsgM_setNowAlpha(&this->m970, ratio);
        fopMsgM_setNowAlpha(&this->m740, ratio);
        fopMsgM_setNowAlpha(&this->m778, ratio);
    }
    f32 half = 0.5f;
    this->m820.pane
        ->rotate((this->m820).mSize.x * half, (this->m820).mSize.y * half, ROTATE_Z, (this->m820).mUserArea + ratio * (iVar9 - (this->m820).mUserArea));
    iVar9 = (this->m7B0).mUserArea;
    if (iVar9 < g_miHIO.mNoteOpenDuration) {
        ratio = (g_miHIO.mNoteOpenRatio * iVar9) / g_miHIO.mNoteOpenDuration;
    } else {
        ratio = 1.0f - g_miHIO.mNoteOpenRatio;
        tmp_ratio = fopMsgM_valueIncrease(g_miHIO.mNoteHoldDuration, open_total - iVar9, 0);
        tmp_ratio = ratio * (1.0f - tmp_ratio);
        ratio = g_miHIO.mNoteOpenRatio + tmp_ratio;
    }
    fopMsgM_paneTrans(&this->m820, dx * ratio, dy * ratio);
    (this->m7B0).mUserArea++;
}

/* 801CC4F8-801CC7D4       .text noteClose__12dMenu_Item_cFv */
void dMenu_Item_c::noteClose() {
    s16 open_final_angle = (int)g_miHIO.mNoteOpenFinalAngle;
    s16 close_final_angle = (int)g_miHIO.mNoteCloseAngle;
    s16 open_total = (s16)(g_miHIO.mNoteOpenDuration + g_miHIO.mNoteHoldDuration);
    s16 close_duration = g_miHIO.mNoteCloseDuration;
    f32 x = g_miHIO.mScreenCenterX;
    f32 y = g_miHIO.mScreenCenterY;
    f32 ddx = 2.0f * x - (this->m820).mPosCenterOrig.x - x;
    f32 ddy = 2.0f * y - (this->m820).mPosCenterOrig.y - y;
    f32 dx = x - (this->m820).mPosCenterOrig.x;
    f32 dy = y - (this->m820).mPosCenterOrig.y;
    f32 ratio = fopMsgM_valueIncrease(close_duration, (this->m7B0).mUserArea - (open_total + 1), 0);
    fopMsgM_paneTrans(&this->m820, dx + ddx * ratio, dy + ddy * ratio);
    f32 half = 0.5f;
    this->m820.pane
        ->rotate((this->m820).mSize.x * half, (this->m820).mSize.y * half, ROTATE_Z, open_final_angle + ratio * (close_final_angle - open_final_angle));
    (this->m7B0).mUserArea = (this->m7B0).mUserArea + 1;
    if ((this->m7B0).mUserArea > (s16)(open_total + close_duration + 1)) {
        fopMsgM_setInitAlpha(&this->m7B0);
        fopMsgM_setInitAlpha(&this->m7E8);
        fopMsgM_setInitAlpha(&this->m820);
        fopMsgM_setNowAlphaZero(&this->m970);
        fopMsgM_setNowAlphaZero(&this->m740);
        fopMsgM_setNowAlphaZero(&this->m778);
        (this->m7E8).mUserArea = 0;
        (this->m7B0).mUserArea = 0;
        this->m820.pane->rotate((this->m820).mSize.x * half, (this->m820).mSize.y * half, ROTATE_Z, (this->m820).mUserArea);
        fopMsgM_paneTrans(&this->m820, 0.0f, 0.0f);
    } else {
        fopMsgM_setNowAlpha(&this->m7B0, ratio = 1.0f - ratio);
        fopMsgM_setNowAlpha(&this->m7E8, ratio);
        fopMsgM_setNowAlpha(&this->m820, ratio);
        fopMsgM_setNowAlpha(&this->m970, ratio);
        fopMsgM_setNowAlpha(&this->m740, ratio);
        fopMsgM_setNowAlpha(&this->m778, ratio);
    }
}

/* 801CC7D4-801CC9D8       .text mainTrans__12dMenu_Item_cFff */
void dMenu_Item_c::mainTrans(f32 x, f32 y) {
    fopMsgM_paneTrans(&mSaveIconPane, x, y);
    fopMsgM_paneTrans(&m14D0, x, y);
    fopMsgM_paneTrans(&m1508, x, y);
    fopMsgM_paneTrans(&mPictureNumPane, x, y);
    fopMsgM_paneTrans(&mArrowNumOnesPane, x, y);
    fopMsgM_paneTrans(&mArrowNumTensPane, x, y);
    fopMsgM_paneTrans(&mBombNumOnesPane, x, y);
    fopMsgM_paneTrans(&mBombNumTensPane, x, y);
    for (int i = 0; i < 21; i++) {
        fopMsgM_paneTrans(&mItemPane[i], x, y);
        fopMsgM_paneTrans(&mItemShadowPane[i], x, y);
    }
    for (int i = 0; i < 3; i++) {
        fopMsgM_paneTrans(&mBowGlowPane[i], x, y);
    }
    for (int i = 0; i < 6; i++) {
        fopMsgM_paneTrans(&mCategoryPane[i], x, y);
    }
    fopMsgM_paneTrans(&m2228, x, y);
    fopMsgM_paneTrans(&m2260, x, y);
    fopMsgM_paneTrans(&m2298, x, y);
    fopMsgM_paneTrans(&m22D0, x, y);
    for (int i = 0; i < 4; i++) {
        fopMsgM_paneTrans(&mCursorPane[i], x, y);
    }
    for (int i = 0; i < 3; i++) {
        if (dComIfGp_getSelectItem(i) != 0xFF) {
            fopMsgM_paneTrans(&mCheckMarkPane[i], x, y);
        }
    }
}

/* 801CC9D8-801CC9FC       .text titleTrans__12dMenu_Item_cFff */
void dMenu_Item_c::titleTrans(f32 x, f32 y) {
    fopMsgM_paneTrans(&this->m9E0, x, y);
}

/* 801CC9FC-801CCA88       .text noteRotate__12dMenu_Item_cFff */
void dMenu_Item_c::noteRotate(f32 y, f32 x) {
    fopMsgM_paneTrans(&m820, 0.0f, y);
    f32 half = 0.5f;
    f32 sizeY = m820.mSize.y;
    f32 centerY = sizeY * half;
    m820.pane->rotate(m820.mSize.x * half, centerY, ROTATE_Z, x);
}

/* 801CCA88-801CCB3C       .text nameTrans__12dMenu_Item_cFff */
void dMenu_Item_c::nameTrans(f32 x, f32 y) {
    fopMsgM_paneTrans(&mItemNamePane, x, y);
    outFont->setLeftUpPos(mItemNamePane.mPosTopLeft.x, mItemNamePane.mPosTopLeft.y);
    outFont->move();
    fopMsgM_paneTrans(&m890, x, y);
    fopMsgM_paneTrans(&m8C8, x, y);
    fopMsgM_paneTrans(&m900, x, y);
    fopMsgM_paneTrans(&m938, x, y);
}

/* 801CCB3C-801CCD74       .text mainOpenProc__12dMenu_Item_cFsss */
void dMenu_Item_c::mainOpenProc(s16 i_timer, s16 i_total, s16 i_xAmount) {
    if (i_total >= i_timer) {
        f32 alpha = fopMsgM_valueIncrease(i_total, i_timer, 0);
        mainTrans(i_xAmount * fopMsgM_valueIncrease(i_total, i_total - i_timer, 0), 0.0f);
        fopMsgM_setNowAlpha(&mSaveIconPane, alpha);
        fopMsgM_setNowAlpha(&m14D0, alpha);
        fopMsgM_setNowAlpha(&m1508, alpha);
        fopMsgM_setNowAlpha(&mPictureNumPane, alpha);
        fopMsgM_setNowAlpha(&mArrowNumOnesPane, alpha);
        fopMsgM_setNowAlpha(&mArrowNumTensPane, alpha);
        fopMsgM_setNowAlpha(&mBombNumOnesPane, alpha);
        fopMsgM_setNowAlpha(&mBombNumTensPane, alpha);
        for (int i = 0; i < 21; i++) {
            fopMsgM_setNowAlpha(&mItemPane[i], alpha);
            fopMsgM_setNowAlpha(&mItemShadowPane[i], alpha);
        }
        for (int i = 0; i < 6; i++) {
            if (itemplaceCheck(i)) {
                fopMsgM_setNowAlpha(&mCategoryPane[i], alpha);
            }
        }
        fopMsgM_setNowAlpha(&m2228, alpha);
        fopMsgM_setNowAlpha(&m2260, alpha);
        fopMsgM_setNowAlpha(&m2298, alpha);
        fopMsgM_setNowAlpha(&m22D0, alpha);
        for (int i = 0; i < 4; i++) {
            fopMsgM_setNowAlpha(&mCursorPane[i], alpha);
        }
        for (int i = 0; i < 3; i++) {
            fopMsgM_setNowAlpha(&mBowGlowPane[i], alpha);
            fopMsgM_setNowAlpha(&mCheckMarkPane[i], alpha);
            if (dComIfGp_getSelectItem(i) != 0xFF) {
                mCheckMarkPane[i].pane->show();
            } else {
                mCheckMarkPane[i].pane->hide();
            }
        }
    }
}

/* 801CCD74-801CCE5C       .text titleOpenProc__12dMenu_Item_cFss */
void dMenu_Item_c::titleOpenProc(s16 i_timer, s16 i_total) {
    /* Nonmatching */
    s16 slide_amount = g_miHIO.mTitleSlideY;
    if (i_total >= i_timer) {
        fopMsgM_valueIncrease(i_total, i_timer, 0);
        titleTrans(0.0f, slide_amount * fopMsgM_valueIncrease(i_total, i_total - i_timer, 0));
        fopMsgM_setInitAlpha(&this->m9A8);
        fopMsgM_setInitAlpha(&this->m9E0);
        if (i_timer == 1) {
            JAIZelBasic::zel_basic->seStart(0x811, (cXyz*)0x0, 0, 0, 1.0f, 1.0f, -1.0f, -1.0f, 0);
        }
    }
}

/* 801CCE5C-801CCF50       .text noteOpenProc__12dMenu_Item_cFss */
void dMenu_Item_c::noteOpenProc(s16 i_timer, s16 i_total) {
    int target_angle;
    int slide_amount;
    f32 ratio;

    target_angle = g_miHIO.mNoteOpenAngle;
    slide_amount = g_miHIO.mNoteSlideY;
    if (i_total >= i_timer) {
        fopMsgM_valueIncrease(i_total, i_timer, 0);
        ratio = fopMsgM_valueIncrease(i_total, i_total - i_timer, 0);
        noteRotate(slide_amount * ratio, m820.mUserArea + ratio * (target_angle - m820.mUserArea));
        for (int i = 0; i < 6; i++) {
            fopMsgM_setInitAlpha(&m7B0);
            fopMsgM_setInitAlpha(&m7E8);
        }
    }
}

/* 801CCF50-801CD004       .text nameOpenProc__12dMenu_Item_cFss */
void dMenu_Item_c::nameOpenProc(s16 i_timer, s16 i_total) {
    /* Nonmatching */
    s16 slide_amount = g_miHIO.mNameSlideY;
    if (i_total >= i_timer) {
        fopMsgM_valueIncrease(i_total, i_timer, 0);
        nameTrans(0.0f, slide_amount * fopMsgM_valueIncrease(i_total, i_total - i_timer, 0));
        fopMsgM_setInitAlpha(&m890);
        fopMsgM_setInitAlpha(&m900);
        fopMsgM_setInitAlpha(&m938);
    }
}

/* 801CD004-801CD04C       .text numberSet__12dMenu_Item_cFP7J2DPaneUc */
void dMenu_Item_c::numberSet(J2DPane* pane, u8 num) {
    /* Nonmatching */
    static char* number[10] = {
        "count_num_0.bti",
        "count_num_1.bti",
        "count_num_2.bti",
        "count_num_3.bti",
        "count_num_4.bti",
        "count_num_5.bti",
        "count_num_6.bti",
        "count_num_7.bti",
        "count_num_8.bti",
        "count_num_9.bti",
    };
    if (num >= 10) {
        num = 0;
    }
    ((J2DPicture*)pane)->changeTexture(number[num], 0);
}

/* 801CD04C-801CD194       .text numberColor__12dMenu_Item_cFP7J2DPaneUc */
void dMenu_Item_c::numberColor(J2DPane* pane, u8 mode) {
    J2DPicture* pic = (J2DPicture*)pane;
    switch (mode) {
        case 1:
            pic->setWhite(JUtility::TColor(0xFFC832FF));
            pic->setBlack(JUtility::TColor(0x1E1E1E00));
            break;
        case 2:
            pic->setWhite(JUtility::TColor(0xB4B4B4FF));
            pic->setBlack(JUtility::TColor(0x1E1E1E00));
            break;
        default:
            pic->setWhite(JUtility::TColor(0xFFFFFFFF));
            pic->setBlack(JUtility::TColor(0x00000000));
            break;
    }
}

/* 801CD194-801CD3FC       .text itemNumberSet__12dMenu_Item_cFv */
void dMenu_Item_c::itemNumberSet() {
    dSv_player_c& player = g_dComIfG_gameInfo.save.getSavedata().getPlayer();

    numberSet(mPictureNumPane.pane, player.getItemRecord().getPictureNum());
    if (player.getItemRecord().getPictureNum() == 0) {
        numberColor(mPictureNumPane.pane, 2);
    } else if (player.getItemRecord().getPictureNum() == 3) {
        numberColor(mPictureNumPane.pane, 1);
    } else {
        numberColor(mPictureNumPane.pane, 0);
    }
    mItemState[0x1e] = player.getItemRecord().getPictureNum();

    u8 arrowNum = player.getItemRecord().getArrowNum();
    if (arrowNum == 0) {
        numberColor(mArrowNumOnesPane.pane, 2);
        numberColor(mArrowNumTensPane.pane, 2);
    } else if (arrowNum == dComIfGs_getArrowMax()) {
        numberColor(mArrowNumOnesPane.pane, 1);
        numberColor(mArrowNumTensPane.pane, 1);
    } else {
        numberColor(mArrowNumOnesPane.pane, 0);
        numberColor(mArrowNumTensPane.pane, 0);
    }
    if (player.getItemRecord().getArrowNum() < 10) {
        mArrowNumTensPane.pane->hide();
    } else {
        numberSet(mArrowNumTensPane.pane, player.getItemRecord().getArrowNum() / 10);
    }
    numberSet(mArrowNumOnesPane.pane, player.getItemRecord().getArrowNum() % 10);
    mItemState[0x1f] = player.getItemRecord().getArrowNum();

    u8 bombNum = player.getItemRecord().getBombNum();
    if (bombNum == 0) {
        numberColor(mBombNumOnesPane.pane, 2);
        numberColor(mBombNumTensPane.pane, 2);
    } else if (bombNum == dComIfGs_getBombMax()) {
        numberColor(mBombNumOnesPane.pane, 1);
        numberColor(mBombNumTensPane.pane, 1);
    } else {
        numberColor(mBombNumOnesPane.pane, 0);
        numberColor(mBombNumTensPane.pane, 0);
    }
    if (player.getItemRecord().getBombNum() < 10) {
        mBombNumTensPane.pane->hide();
    } else {
        numberSet(mBombNumTensPane.pane, player.getItemRecord().getBombNum() / 10);
    }
    numberSet(mBombNumOnesPane.pane, player.getItemRecord().getBombNum() % 10);
    mItemState[0x20] = player.getItemRecord().getBombNum();
}

/* 801CD3FC-801CDA14       .text itemCheck__12dMenu_Item_cFi */
void dMenu_Item_c::itemCheck(int i_no) {
    u8 itemNo = dComIfGs_getItem(i_no);
    if (itemNo != dItemNo_NONE_e) {
        if (recollectBossCheck() && (itemNo == dItemNo_WATER_BOTTLE_e || itemNo == dItemNo_FIREFLY_BOTTLE_e || itemNo == dItemNo_FOREST_WATER_e)) {
            mItemPane[i_no].pane->hide();
            mItemShadowPane[i_no].pane->hide();
        }
        if (itemNo == dItemNo_MAGIC_ARROW_e) {
            mBowGlowPane[0].pane->show();
            mBowGlowPane[1].pane->show();
            mBowGlowPane[2].pane->hide();
            itemNo = dItemNo_BOW_e;
        } else if (itemNo == dItemNo_LIGHT_ARROW_e) {
            mBowGlowPane[0].pane->show();
            mBowGlowPane[1].pane->show();
            mBowGlowPane[2].pane->show();
            itemNo = dItemNo_BOW_e;
        } else if (itemNo == dItemNo_FOREST_WATER_e &&
                   !(recollectBossCheck() && (itemNo == dItemNo_WATER_BOTTLE_e || itemNo == dItemNo_FIREFLY_BOTTLE_e || itemNo == dItemNo_FOREST_WATER_e)))
        {
            cXyz pos;
            pos.set(mItemPane[i_no].mPosCenter.x - 320.0f, mItemPane[i_no].mPosCenter.y - 240.0f, 0.0f);
            if (mpEmitter[0] == NULL) {
                mpEmitter[0] = dComIfGp_particle_set2DmenuFore(0x2d, &pos);
            }
            if (mpEmitter[1] == NULL) {
                mpEmitter[1] = dComIfGp_particle_set2DmenuFore(0x2d, &pos);
            }
        }
        JKRReadTypeResource(mItemTexBuffer[i_no], 0xc00, 'TIMG', dItem_data::getTexture(itemNo), dComIfGp_getItemIconArchive());
        DCStoreRangeNoSync(mItemTexBuffer[i_no], 0xc00);
        ((J2DPicture*)mItemPane[i_no].pane)->changeTexture((ResTIMG*)mItemTexBuffer[i_no], 0);
        ((J2DPicture*)mItemShadowPane[i_no].pane)->changeTexture((ResTIMG*)mItemTexBuffer[i_no], 0);
        if (i_no == 8) {
            if (dComIfGs_getItem(i_no) == dItemNo_PICTO_BOX_e) {
                mItemPane[i_no].pane->show();
                mItemShadowPane[i_no].pane->show();
                mPictureNumPane.pane->show();
            } else if (dComIfGs_getItem(i_no) == dItemNo_DELUXE_PICTO_BOX_e) {
                mItemPane[i_no].pane->show();
                mItemShadowPane[i_no].pane->show();
                mPictureNumPane.pane->show();
            } else {
                mItemPane[i_no].pane->hide();
                mItemShadowPane[i_no].pane->hide();
                mPictureNumPane.pane->hide();
            }
        }
        mItemState[i_no + 6] = dComIfGs_getItem(i_no);
    } else {
        mItemPane[i_no].pane->hide();
        mItemShadowPane[i_no].pane->hide();
        if (i_no == 8) {
            mPictureNumPane.pane->hide();
        } else if (i_no == 0xc) {
            mArrowNumOnesPane.pane->hide();
            mArrowNumTensPane.pane->hide();
        } else if (i_no == 0xd) {
            mBombNumOnesPane.pane->hide();
            mBombNumTensPane.pane->hide();
        }
    }
}

/* 801CDA14-801CDB14       .text itemBitCheck__12dMenu_Item_cFb */
void dMenu_Item_c::itemBitCheck(bool i_force) {
    u8 item_no;
    dSv_player_item_c* item_ptr;
    int i = 0;
    item_ptr = &g_dComIfG_gameInfo.save.getSavedata().getPlayer().getItem();
    for (; i < 21; i++) {
        item_no = dComIfGs_getItem(i);
        if ((this->mItemState[i + 6] != item_no) || (i_force)) {
            itemCheck(i);
        }
        item_ptr = (dSv_player_item_c*)(item_ptr->mItems + 1);
    }
}

/* 801CDB14-801CDC34       .text arrowLightAnime__12dMenu_Item_cFv */
void dMenu_Item_c::arrowLightAnime() {
    this->mBowGlowPane[0].mUserArea++;
    if (this->mBowGlowPane[0].mUserArea >= 0x78) {
        this->mBowGlowPane[0].mUserArea = 0;
    }
    s16 count = this->mBowGlowPane[0].mUserArea;
    f32 rate;
    if (count < 0x3c) {
        rate = fopMsgM_valueIncrease(0x3c, count, 0);
    } else {
        rate = fopMsgM_valueIncrease(0x3c, 0x78 - count, 0);
    }
    f32 scale = 1.0f - rate * 0.39999998f;
    u8 alpha = this->mBowGlowPane[0].mInitAlpha;
    f32 newAlpha = alpha - (alpha - 50.0f) * rate;
    for (int i = 0; i < 3; i++) {
        fopMsgM_paneScaleXY(&this->mBowGlowPane[i], scale);
        this->mBowGlowPane[i].mNowAlpha = newAlpha;
    }
}

/* 801CDC34-801CDCF0       .text bottleFwaterCheck__12dMenu_Item_cFv */
int dMenu_Item_c::bottleFwaterCheck() {
    for (int i = 0; i < dInvSlot_BOTTLE_COUNT_e; i++) {
        int slot = dInvSlot_BOTTLE0_e + i;
        if (dComIfGs_getItem(slot) == dItemNo_FOREST_WATER_e) {
            return slot;
        }
    }
    return 0;
}

/* 801CDCF0-801CDDC0       .text recollectBossCheck__12dMenu_Item_cFv */
BOOL dMenu_Item_c::recollectBossCheck() {

    if (dStage_stagInfo_GetSTType(dComIfGp_getStageStagInfo()) == dStageType_BOSS_e) {
        const char* name = dComIfGp_getStartStageName();
        if (((strcmp(name, "Xboss0") == 0) || (strcmp(name, "Xboss1") == 0)) || (strcmp(name, "Xboss2") == 0) || (strcmp(name, "Xboss3") == 0)) {
            return TRUE;
        }
    }
    return FALSE;
}

/* 801CDDC0-801CF08C       .text cornerMove__12dMenu_Item_cFv */
void dMenu_Item_c::cornerMove() {
    J2DWindow::TContentsColor contents;
    JUtility::TColor white;

    mCornerAnimTimer[0]++;
    if (mCornerAnimTimer[0] >= 0xF0) {
        mCornerAnimTimer[0] = 0;
    }

    f32 t = fopMsgM_valueIncrease(0x3C, mCornerAnimTimer[0] % 0x3C, 2);
    if (mCornerAnimTimer[0] < 0x3C) {
        contents.mTL.r = mCornerColorTL.r + t * (mCornerColorBL.r - mCornerColorTL.r);
        contents.mTL.g = mCornerColorTL.g + t * (mCornerColorBL.g - mCornerColorTL.g);
        contents.mTL.b = mCornerColorTL.b + t * (mCornerColorBL.b - mCornerColorTL.b);
        contents.mTL.a = mCornerColorTL.a + t * (mCornerColorBL.a - mCornerColorTL.a);
        contents.mTR.r = mCornerColorTR.r + t * (mCornerColorTL.r - mCornerColorTR.r);
        contents.mTR.g = mCornerColorTR.g + t * (mCornerColorTL.g - mCornerColorTR.g);
        contents.mTR.b = mCornerColorTR.b + t * (mCornerColorTL.b - mCornerColorTR.b);
        contents.mTR.a = mCornerColorTR.a + t * (mCornerColorTL.a - mCornerColorTR.a);
        contents.mBL.r = mCornerColorBL.r + t * (mCornerColorBR.r - mCornerColorBL.r);
        contents.mBL.g = mCornerColorBL.g + t * (mCornerColorBR.g - mCornerColorBL.g);
        contents.mBL.b = mCornerColorBL.b + t * (mCornerColorBR.b - mCornerColorBL.b);
        contents.mBL.a = mCornerColorBL.a + t * (mCornerColorBR.a - mCornerColorBL.a);
        contents.mBR.r = mCornerColorBR.r + t * (mCornerColorTR.r - mCornerColorBR.r);
        contents.mBR.g = mCornerColorBR.g + t * (mCornerColorTR.g - mCornerColorBR.g);
        contents.mBR.b = mCornerColorBR.b + t * (mCornerColorTR.b - mCornerColorBR.b);
        contents.mBR.a = mCornerColorBR.a + t * (mCornerColorTR.a - mCornerColorBR.a);
    } else if (mCornerAnimTimer[0] < 0x78) {
        contents.mTR.r = mCornerColorTL.r + t * (mCornerColorBL.r - mCornerColorTL.r);
        contents.mTR.g = mCornerColorTL.g + t * (mCornerColorBL.g - mCornerColorTL.g);
        contents.mTR.b = mCornerColorTL.b + t * (mCornerColorBL.b - mCornerColorTL.b);
        contents.mTR.a = mCornerColorTL.a + t * (mCornerColorBL.a - mCornerColorTL.a);
        contents.mBR.r = mCornerColorTR.r + t * (mCornerColorTL.r - mCornerColorTR.r);
        contents.mBR.g = mCornerColorTR.g + t * (mCornerColorTL.g - mCornerColorTR.g);
        contents.mBR.b = mCornerColorTR.b + t * (mCornerColorTL.b - mCornerColorTR.b);
        contents.mBR.a = mCornerColorTR.a + t * (mCornerColorTL.a - mCornerColorTR.a);
        contents.mTL.r = mCornerColorBL.r + t * (mCornerColorBR.r - mCornerColorBL.r);
        contents.mTL.g = mCornerColorBL.g + t * (mCornerColorBR.g - mCornerColorBL.g);
        contents.mTL.b = mCornerColorBL.b + t * (mCornerColorBR.b - mCornerColorBL.b);
        contents.mTL.a = mCornerColorBL.a + t * (mCornerColorBR.a - mCornerColorBL.a);
        contents.mBL.r = mCornerColorBR.r + t * (mCornerColorTR.r - mCornerColorBR.r);
        contents.mBL.g = mCornerColorBR.g + t * (mCornerColorTR.g - mCornerColorBR.g);
        contents.mBL.b = mCornerColorBR.b + t * (mCornerColorTR.b - mCornerColorBR.b);
        contents.mBL.a = mCornerColorBR.a + t * (mCornerColorTR.a - mCornerColorBR.a);
    } else if (mCornerAnimTimer[0] < 0xB4) {
        contents.mBR.r = mCornerColorTL.r + t * (mCornerColorBL.r - mCornerColorTL.r);
        contents.mBR.g = mCornerColorTL.g + t * (mCornerColorBL.g - mCornerColorTL.g);
        contents.mBR.b = mCornerColorTL.b + t * (mCornerColorBL.b - mCornerColorTL.b);
        contents.mBR.a = mCornerColorTL.a + t * (mCornerColorBL.a - mCornerColorTL.a);
        contents.mBL.r = mCornerColorTR.r + t * (mCornerColorTL.r - mCornerColorTR.r);
        contents.mBL.g = mCornerColorTR.g + t * (mCornerColorTL.g - mCornerColorTR.g);
        contents.mBL.b = mCornerColorTR.b + t * (mCornerColorTL.b - mCornerColorTR.b);
        contents.mBL.a = mCornerColorTR.a + t * (mCornerColorTL.a - mCornerColorTR.a);
        contents.mTR.r = mCornerColorBL.r + t * (mCornerColorBR.r - mCornerColorBL.r);
        contents.mTR.g = mCornerColorBL.g + t * (mCornerColorBR.g - mCornerColorBL.g);
        contents.mTR.b = mCornerColorBL.b + t * (mCornerColorBR.b - mCornerColorBL.b);
        contents.mTR.a = mCornerColorBL.a + t * (mCornerColorBR.a - mCornerColorBL.a);
        contents.mTL.r = mCornerColorBR.r + t * (mCornerColorTR.r - mCornerColorBR.r);
        contents.mTL.g = mCornerColorBR.g + t * (mCornerColorTR.g - mCornerColorBR.g);
        contents.mTL.b = mCornerColorBR.b + t * (mCornerColorTR.b - mCornerColorBR.b);
        contents.mTL.a = mCornerColorBR.a + t * (mCornerColorTR.a - mCornerColorBR.a);
    } else {
        contents.mBL.r = mCornerColorTL.r + t * (mCornerColorBL.r - mCornerColorTL.r);
        contents.mBL.g = mCornerColorTL.g + t * (mCornerColorBL.g - mCornerColorTL.g);
        contents.mBL.b = mCornerColorTL.b + t * (mCornerColorBL.b - mCornerColorTL.b);
        contents.mBL.a = mCornerColorTL.a + t * (mCornerColorBL.a - mCornerColorTL.a);
        contents.mTL.r = mCornerColorTR.r + t * (mCornerColorTL.r - mCornerColorTR.r);
        contents.mTL.g = mCornerColorTR.g + t * (mCornerColorTL.g - mCornerColorTR.g);
        contents.mTL.b = mCornerColorTR.b + t * (mCornerColorTL.b - mCornerColorTR.b);
        contents.mTL.a = mCornerColorTR.a + t * (mCornerColorTL.a - mCornerColorTR.a);
        contents.mBR.r = mCornerColorBL.r + t * (mCornerColorBR.r - mCornerColorBL.r);
        contents.mBR.g = mCornerColorBL.g + t * (mCornerColorBR.g - mCornerColorBL.g);
        contents.mBR.b = mCornerColorBL.b + t * (mCornerColorBR.b - mCornerColorBL.b);
        contents.mBR.a = mCornerColorBL.a + t * (mCornerColorBR.a - mCornerColorBL.a);
        contents.mTR.r = mCornerColorBR.r + t * (mCornerColorTR.r - mCornerColorBR.r);
        contents.mTR.g = mCornerColorBR.g + t * (mCornerColorTR.g - mCornerColorBR.g);
        contents.mTR.b = mCornerColorBR.b + t * (mCornerColorTR.b - mCornerColorBR.b);
        contents.mTR.a = mCornerColorBR.a + t * (mCornerColorTR.a - mCornerColorBR.a);
    }

    ((J2DWindow*)m14D0.pane)->setContentsColor(contents);

    mCornerAnimTimer[1]++;
    if (mCornerAnimTimer[1] >= 0x28) {
        mCornerAnimTimer[1] = 0;
    }
    if (mCornerAnimTimer[1] < 0x14) {
        t = fopMsgM_valueIncrease(0x14, mCornerAnimTimer[1], 0);
    } else {
        t = fopMsgM_valueIncrease(0x14, 0x28 - mCornerAnimTimer[1], 0);
    }

    white.r = 0xFF;
    white.g = 128.0f - t * -42.0f;
    white.b = 0;
    white.a = 0xFF;
    ((J2DWindow*)m14D0.pane)->setWhite(white);
}

/* 801CF08C-801CF12C       .text equipBeastItem__12dMenu_Item_cFi */
int dMenu_Item_c::equipBeastItem(int i_no) {
    u8 item = dComIfGs_getItemBeast(i_no);
    u8 idx = 0;
    switch (item) {
        case dItemNo_SKULL_NECKLACE_e:
            idx = 0;
            break;
        case dItemNo_BOKOBABA_SEED_e:
            idx = 1;
            break;
        case dItemNo_GOLDEN_FEATHER_e:
            idx = 2;
            break;
        case dItemNo_KNIGHTS_CREST_e:
            idx = 3;
            break;
        case dItemNo_RED_JELLY_e:
            idx = 4;
            break;
        case dItemNo_GREEN_JELLY_e:
            idx = 5;
            break;
        case dItemNo_BLUE_JELLY_e:
            idx = 6;
            break;
        case dItemNo_JOY_PENDANT_e:
            idx = 7;
            break;
    }
    return idx;
}

/* 801CF12C-801CF510       .text _create__12dMenu_Item_cFv */
void dMenu_Item_c::_create() {
    scrn = new J2DScreen();
    JUT_ASSERT(0xa57, scrn != 0);
    scrn->set("menu_item_02.blo", mpArc);

    stick = new STControl(5, 2, 3, 2);
    JUT_ASSERT(0xa5b, stick != 0);
    stick->setWaitParm(5, 2, 3, 2, 0.9f, 0.5f, 0, 0x800);

    outFont = new dDlst_2DOutFont_c();
    JUT_ASSERT(0xa5f, outFont != 0);
    outFont->m74 = 1;

    dMs_c = new dMenu_save_c();
    JUT_ASSERT(0xa63, dMs_c != 0);
    dMs_c->useType = 0;
    dMs_c->_create();

    mItemMode = 0;
    mpEmitter[0] = NULL;
    mpEmitter[1] = NULL;
    screenSet();
    initialize();
    g_miHIO.mNo = mDoHIO_createChild("アイテム画面", &g_miHIO); // "Item Screen"

    for (int i = 0; i < 4; i++) {
        ((J2DPicture*)mCursorPane[i].pane)->append("cursor_00_02.bti", 1.0f);
        mCursorOffsetX[i] = mCursorPane[i].mPosCenterOrig.x - mItemPane[0].mPosCenterOrig.x;
        mCursorOffsetY[i] = mCursorPane[i].mPosCenterOrig.y - mItemPane[0].mPosCenterOrig.y;
    }
    for (int i = 0; i < 15; i++) {
        ((J2DPicture*)m0B0[i].pane)->changeTexture("font_07_02.bti", 0);
        fopMsgM_blendInit(&m0B0[i], "font_00.bti");
    }

    mItemState[0] = 0;
    mItemState[1] = 0;
    mItemState[2] = 0;
    mItemState[0x20] = 0;
    mItemState[0x1f] = 0;
    mItemState[0x1e] = 0;
    mItemState[4] = dItemBtn_NONE_e;
    mItemState[3] = dItemBtn_NONE_e;
    mItemState[5] = dItemBtn_NONE_e;

    for (int i = 0; i < 0x15; i++) {
        itemCheck(i);
    }
    cursorAnime();
}

/* 801CF510-801CF618       .text _delete__12dMenu_Item_cFv */
void dMenu_Item_c::_delete() {
    for (int i = 0; i < 2; i++) {
        if (mpEmitter[i] != NULL) {
            mpEmitter[i]->becomeInvalidEmitter();
            mpEmitter[i]->quitImmortalEmitter();
            mpEmitter[i] = NULL;
        }
    }
    delete scrn;
    delete stick;
    if (outFont != NULL) {
        delete outFont;
    }
    dMs_c->_delete();
    delete dMs_c;
    mpArc->removeResourceAll();
    mDoHIO_deleteChild(g_miHIO.mNo);
}

/* 801CF618-801D0524       .text _move__12dMenu_Item_cFv */
void dMenu_Item_c::_move() {
    u8 oldItem = mNowItem;
    itemBitCheck(false);
    if (mItemMode == 0) {
        if (noteCheck() == 0) {
            if (!CPad_CHECK_TRIG_START(0) && !mDoCPd_R_LOCK_BUTTON(0) && !mDoCPd_L_LOCK_BUTTON(0)) {
                if (CPad_CHECK_TRIG_A(0)) {
                    if (dMeter_subWinFlag() && mNowItem == 0xff) {
                        subWindowDelete();
                        JAIZelBasic::zel_basic->seStart(0x84b, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
                    } else if (mNowItem == 0x15) {
                        mItemMode = 1;
                        dMs_c->initialize();
                        JAIZelBasic::zel_basic->seStart(0x84c, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
                    } else if (dComIfGs_getItem(mNowItem) != dItemNo_NONE_e) {
                        if (!(recollectBossCheck() &&
                              (dComIfGs_getItem(mNowItem) == dItemNo_WATER_BOTTLE_e || dComIfGs_getItem(mNowItem) == dItemNo_FIREFLY_BOTTLE_e ||
                               dComIfGs_getItem(mNowItem) == dItemNo_FOREST_WATER_e)))
                        {
                            fopMsgM_setInitAlpha(&m740);
                            fopMsgM_setInitAlpha(&m778);
                            fopMsgM_setInitAlpha(&m7B0);
                            fopMsgM_setInitAlpha(&m7E8);
                            fopMsgM_setInitAlpha(&m820);
                            m7E8.mUserArea = 1;
                            m7B0.mUserArea = 1;
                            itemnoteSet();
                            JAIZelBasic::zel_basic->seStart(0x8b6, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
                        }
                    }
                } else if (CPad_CHECK_TRIG_B(0)) {
                    if (dMeter_subWinFlag()) {
                        subWindowDelete();
                        JAIZelBasic::zel_basic->seStart(0x84b, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
                    }
                } else if (CPad_CHECK_TRIG_X(0) || CPad_CHECK_TRIG_Y(0) || CPad_CHECK_TRIG_Z(0)) {
                    if (dMeter_subWinFlag() && mNowItem == 0xff) {
                        subWindowDelete();
                        JAIZelBasic::zel_basic->seStart(0x84b, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
                    } else if (mNowItem != 0x15 && dComIfGs_getItem(mNowItem) != dItemNo_NONE_e) {
                        if (dMeter_subWinFlag()) {
                            if (mNowItem == 0xff) {
                                subWindowDelete();
                                JAIZelBasic::zel_basic->seStart(0x84b, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
                            } else {
                                subItemDecide();
                            }
                        } else {
                            if (!(recollectBossCheck() &&
                                  (dComIfGs_getItem(mNowItem) == dItemNo_WATER_BOTTLE_e || dComIfGs_getItem(mNowItem) == dItemNo_FIREFLY_BOTTLE_e ||
                                   dComIfGs_getItem(mNowItem) == dItemNo_FOREST_WATER_e)))
                            {
                                itemDecide();
                            }
                        }
                    }
                } else {
                    if (dMeter_subWinFlag()) {
                        cursorSubMove();
                    } else {
                        cursorMainMove();
                    }
                    itemScale();
                    if (mNowItem != oldItem && oldItem == 0xc) {
                        for (int i = 0; i < 3; i++) {
                            fopMsgM_paneTrans(&mBowGlowPane[i], 0.0f, 0.0f);
                        }
                    }
                }
            }
        } else {
            noteAppear();
        }
        if (mItemState[4] != dItemBtn_NONE_e) {
            itemMove();
        }
        if (mNowItem == 0x15) {
            itemnameMove();
        } else if (dComIfGs_getItem(mNowItem) != dItemNo_NONE_e &&
                   !(recollectBossCheck() && (dComIfGs_getItem(mNowItem) == dItemNo_WATER_BOTTLE_e || dComIfGs_getItem(mNowItem) == dItemNo_FIREFLY_BOTTLE_e ||
                                              dComIfGs_getItem(mNowItem) == dItemNo_FOREST_WATER_e)))
        {
            itemnameMove();
        } else {
            fopMsgM_setNowAlphaZero(&m890);
            fopMsgM_setNowAlphaZero(&m8C8);
            fopMsgM_setNowAlphaZero(&mItemNamePane);
        }
        outFontMove();
        cursorAnime();
        cornerMove();
        if (g_dComIfG_gameInfo.save.getSavedata().getPlayer().getItem().getItem(dInvSlot_BOW_e) == dItemNo_MAGIC_ARROW_e ||
            g_dComIfG_gameInfo.save.getSavedata().getPlayer().getItem().getItem(dInvSlot_BOW_e) == dItemNo_LIGHT_ARROW_e)
        {
            arrowLightAnime();
        }
        checkMove();
        int slot = bottleFwaterCheck();
        if (slot != 0) {
            for (int i = 0; i < 2; i++) {
                if (mpEmitter[i] != NULL) {
                    cXyz pos;
                    pos.set(mItemPane[slot].mPosCenterOrig.x - 320.0f, mItemPane[slot].mPosCenterOrig.y - 240.0f, 0.0f);
                    mpEmitter[i]->setGlobalTranslation(pos);
                    mpEmitter[i]->playDrawParticle();
                    mpEmitter[i]->setGlobalAlpha(0xff);
                }
            }
        }
    } else if (mItemMode == 1) {
        switch (dMs_c->saveStatus) {
            case 0:
                mItemMode = 0;
                break;
            case 1:
                dMs_c->_open();
                break;
            case 2:
                dMs_c->_move();
                break;
            case 3:
                dMs_c->_close();
                break;
        }
        if (bottleFwaterCheck()) {
            for (int i = 0; i < 2; i++) {
                if (mpEmitter[i] != NULL) {
                    mpEmitter[i]->setGlobalAlpha(0);
                }
            }
        }
        dComIfGp_setAStatusForce(7);
    }

    if (mNowItem != 0x15) {
        if (dComIfGs_getItem(mNowItem) != dItemNo_NONE_e) {
            dComIfGp_setDoStatusForce(0x21);
        } else {
            dComIfGp_setDoStatusForce(0);
            dComIfGp_setDoStatus(0);
        }
    } else {
        dComIfGp_setDoStatusForce(0x17);
    }
}

/* 801D0524-801D0F50       .text _draw__12dMenu_Item_cFv */
void dMenu_Item_c::_draw() {
    if (m2422 == 0) {
        fopMsgM_setAlpha(&m740);
        fopMsgM_setAlpha(&m778);
        fopMsgM_setAlpha(&m7B0);
        fopMsgM_setAlpha(&m7E8);
        fopMsgM_setAlpha(&m820);
        outFont->setAlpha(mItemNamePane.mNowAlpha);
        fopMsgM_setAlpha(&m890);
        fopMsgM_setAlpha(&m8C8);
        fopMsgM_setAlpha(&m900);
        fopMsgM_setAlpha(&m938);
        fopMsgM_setAlpha(&m970);
        fopMsgM_setAlpha(&m9A8);
        fopMsgM_setAlpha(&m9E0);
        for (int i = 0; i < 4; i++) {
            fopMsgM_setAlpha(&mCursorPane[i]);
        }
        for (int i = 0; i < 8; i++) {
            fopMsgM_setAlpha(&mSubItemNumOnesPane[i]);
            fopMsgM_setAlpha(&mSubItemNumTensPane[i]);
            fopMsgM_setAlpha(&mSubItemPane[i]);
            fopMsgM_setAlpha(&mSubItemShadowPane[i]);
        }
        fopMsgM_setAlpha(&mSubItemBackPane);
        fopMsgM_setAlpha(&mSubItemBackShadowPane);
        for (int i = 0; i < 9; i++) {
            fopMsgM_setAlpha(&m1268[i]);
        }
        fopMsgM_setAlpha(&m1460);
        fopMsgM_setAlpha(&mSaveIconPane);
        fopMsgM_setAlpha(&m14D0);
        fopMsgM_setAlpha(&m1508);
        fopMsgM_setAlpha(&mPictureNumPane);
        fopMsgM_setAlpha(&mArrowNumOnesPane);
        fopMsgM_setAlpha(&mArrowNumTensPane);
        fopMsgM_setAlpha(&mBombNumOnesPane);
        fopMsgM_setAlpha(&mBombNumTensPane);
        for (int i = 0; i < 0x15; i++) {
            fopMsgM_setAlpha(&mItemPane[i]);
            fopMsgM_setAlpha(&mItemShadowPane[i]);
        }
        for (int i = 0; i < 3; i++) {
            fopMsgM_setAlpha(&mBowGlowPane[i]);
            fopMsgM_setAlpha(&mCheckMarkPane[i]);
        }
        for (int i = 0; i < 6; i++) {
            fopMsgM_setAlpha(&mCategoryPane[i]);
        }
        fopMsgM_setAlpha(&m2228);
        fopMsgM_setAlpha(&m2260);
        fopMsgM_setAlpha(&m2298);
        fopMsgM_setAlpha(&m22D0);
    } else {
        f32 t = fopMsgM_valueIncrease(10, mTimer, 0);
        if (mTriggerInfo != 1 && mTriggerInfo != 2) {
            alphaChange(&m740, t);
            alphaChange(&m778, t);
            alphaChange(&m7B0, t);
            alphaChange(&m7E8, t);
            alphaChange(&m820, t);
            outFont->setAlpha((f32)mItemNamePane.mNowAlpha * t);
            alphaChange(&m890, t);
            alphaChange(&m8C8, t);
            alphaChange(&m900, t);
            alphaChange(&m938, t);
            alphaChange(&m9A8, t);
            alphaChange(&m9E0, t);
        }
        alphaChange(&m970, t);
        for (int i = 0; i < 4; i++) {
            alphaChange(&mCursorPane[i], t);
        }
        for (int i = 0; i < 8; i++) {
            alphaChange(&mSubItemNumOnesPane[i], t);
            alphaChange(&mSubItemNumTensPane[i], t);
            alphaChange(&mSubItemPane[i], t);
            alphaChange(&mSubItemShadowPane[i], t);
        }
        alphaChange(&mSubItemBackPane, t);
        alphaChange(&mSubItemBackShadowPane, t);
        for (int i = 0; i < 9; i++) {
            alphaChange(&m1268[i], t);
        }
        alphaChange(&m1460, t);
        alphaChange(&mSaveIconPane, t);
        alphaChange(&m14D0, t);
        alphaChange(&m1508, t);
        alphaChange(&mPictureNumPane, t);
        alphaChange(&mArrowNumOnesPane, t);
        alphaChange(&mArrowNumTensPane, t);
        alphaChange(&mBombNumOnesPane, t);
        alphaChange(&mBombNumTensPane, t);
        for (int i = 0; i < 0x15; i++) {
            alphaChange(&mItemPane[i], t);
            alphaChange(&mItemShadowPane[i], t);
        }
        for (int i = 0; i < 3; i++) {
            alphaChange(&mBowGlowPane[i], t);
            alphaChange(&mCheckMarkPane[i], t);
        }
        for (int i = 0; i < 6; i++) {
            alphaChange(&mCategoryPane[i], t);
        }
        alphaChange(&m2228, t);
        alphaChange(&m2260, t);
        alphaChange(&m2298, t);
        alphaChange(&m22D0, t);
    }
    outFontDraw();
    J2DOrthoGraph* ctx = dComIfGp_getCurrentGrafPort();
    ctx->setPort();
    scrn->draw(0.0f, 0.0f, (J2DGrafContext*)ctx);
    dMs_c->_draw();
}

/* 801D0F50-801D1438       .text _open__12dMenu_Item_cFv */
bool dMenu_Item_c::_open() {
    /* Nonmatching */
    s16 x = g_miHIO.mMainSlideX;
    bool ret = false;
    if (mTimer == 0) {
        for (int i = 0; i < 2; i++) {
            strcpy(name[i], "");
            strcpy(note[i], "");
            ((J2DTextBox*)(&m890)[i].pane)->setString(name[i]);
        }
        ((J2DTextBox*)m778.pane)->setString(note[0]);
        ((J2DTextBox*)m740.pane)->setString(note[1]);
        itemnameSet();
        if (mNowItem != 0x15 &&
            !(recollectBossCheck() && (dComIfGs_getItem(mNowItem) == dItemNo_WATER_BOTTLE_e || dComIfGs_getItem(mNowItem) == dItemNo_FIREFLY_BOTTLE_e ||
                                       dComIfGs_getItem(mNowItem) == dItemNo_FOREST_WATER_e)))
        {
            itemnoteSet();
            if (dComIfGs_getItem(mNowItem) != dItemNo_NONE_e) {
                dComIfGp_setDoStatusForce(0x21);
            } else {
                dComIfGp_setDoStatusForce(0);
                dComIfGp_setDoStatus(0);
            }
        } else {
            dComIfGp_setDoStatusForce(0x17);
        }
    }
    mTimer = mTimer + 1;
    if (mTimer <= 10 && mTimer > 0) {
        if (mTriggerInfo == 2) {
            mainOpenProc(mTimer, 10, x);
        } else {
            mainOpenProc(mTimer, 10, -x);
        }
        titleOpenProc(mTimer, 10);
        noteOpenProc(mTimer, 10);
        nameOpenProc(mTimer, 10);
    }
    if (mTimer >= 10) {
        ret = true;
        JAIZelBasic::zel_basic->seStart(0x813, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
    }
    return ret;
}

inline f32 dMenu_lerp(s16 a, s16 b, f32 t) {
    return a + t * (b - a);
}

inline f32 dMenu_scale(s16 a, f32 t) {
    return a * t;
}

/* 801D1438-801D1CD4       .text _close__12dMenu_Item_cFv */
bool dMenu_Item_c::_close() {
    bool ret = false;
    f32 note_ratio;
    mTimer--;
    f32 main_offset_x = g_miHIO.mMainSlideX * fopMsgM_valueIncrease(10, 10 - mTimer, 0);
    f32 title_offset_y = g_miHIO.mTitleSlideY * fopMsgM_valueIncrease(10, 10 - mTimer, 0);
    f32 name_offset_y = g_miHIO.mNameSlideY * fopMsgM_valueIncrease(10, 10 - mTimer, 0);
    note_ratio = fopMsgM_valueIncrease(10, 10 - mTimer, 0);
    f32 emitter_alpha_ratio = fopMsgM_valueIncrease(10, mTimer, 0);

    for (int i = 0; i < 2; i++) {
        if (mpEmitter[i] != NULL) {
            mpEmitter[i]->mGlobalPrmColor.a = 255.0f * emitter_alpha_ratio;
        }
    }

    if (mTriggerInfo == 2) {
        mainTrans(-main_offset_x, 0.0f);
        titleTrans(0.0f, title_offset_y);
        noteRotate(dMenu_scale(g_miHIO.mNoteSlideY, note_ratio), dMenu_lerp(m820.mUserArea, g_miHIO.mNoteOpenAngle, note_ratio));
        nameTrans(0.0f, name_offset_y);
    } else if (mTriggerInfo == 1) {
        mainTrans(main_offset_x, 0.0f);
        titleTrans(0.0f, title_offset_y);
        noteRotate(dMenu_scale(g_miHIO.mNoteSlideY, note_ratio), dMenu_lerp(m820.mUserArea, g_miHIO.mNoteOpenAngle, note_ratio));
        nameTrans(0.0f, name_offset_y);
    }

    if (mTimer > 0) {
        m2422 = 1;
    } else {
        ret = true;
        m2422 = 0;

        for (int i = 0; i < 15; i++) {
            fopMsgM_setNowAlphaZero(&m0B0[i]);
        }
        fopMsgM_setNowAlphaZero(&m740);
        fopMsgM_setNowAlphaZero(&m778);
        fopMsgM_setNowAlphaZero(&m7B0);
        fopMsgM_setNowAlphaZero(&m7E8);
        fopMsgM_setNowAlphaZero(&m820);
        fopMsgM_setNowAlphaZero(&mItemNamePane);
        fopMsgM_setNowAlphaZero(&m890);
        fopMsgM_setNowAlphaZero(&m8C8);
        fopMsgM_setNowAlphaZero(&m900);
        fopMsgM_setNowAlphaZero(&m938);
        fopMsgM_setNowAlphaZero(&m970);
        fopMsgM_setNowAlphaZero(&m9A8);
        fopMsgM_setNowAlphaZero(&m9E0);

        for (int i = 0; i < 4; i++) {
            fopMsgM_setNowAlphaZero(&mCursorPane[i]);
        }

        for (int i = 0; i < 8; i++) {
            fopMsgM_setNowAlphaZero(&mSubItemNumOnesPane[i]);
            fopMsgM_setNowAlphaZero(&mSubItemNumTensPane[i]);
            fopMsgM_setNowAlphaZero(&mSubItemPane[i]);
            fopMsgM_setNowAlphaZero(&mSubItemShadowPane[i]);
        }
        fopMsgM_setNowAlphaZero(&mSubItemBackPane);
        fopMsgM_setNowAlphaZero(&mSubItemBackShadowPane);

        for (int i = 0; i < 9; i++) {
            fopMsgM_setNowAlphaZero(&m1268[i]);
        }
        fopMsgM_setNowAlphaZero(&m1460);
        fopMsgM_setNowAlphaZero(&mSaveIconPane);
        fopMsgM_setNowAlphaZero(&m14D0);
        fopMsgM_setNowAlphaZero(&m1508);
        fopMsgM_setNowAlphaZero(&mPictureNumPane);
        fopMsgM_setNowAlphaZero(&mArrowNumOnesPane);
        fopMsgM_setNowAlphaZero(&mArrowNumTensPane);
        fopMsgM_setNowAlphaZero(&mBombNumOnesPane);
        fopMsgM_setNowAlphaZero(&mBombNumTensPane);

        for (int i = 0; i < 0x15; i++) {
            fopMsgM_setNowAlphaZero(&mItemPane[i]);
            fopMsgM_setNowAlphaZero(&mItemShadowPane[i]);
        }

        for (int i = 0; i < 3; i++) {
            fopMsgM_setNowAlphaZero(&mCheckMarkPane[i]);
        }

        for (int i = 0; i < 6; i++) {
            fopMsgM_setNowAlphaZero(&mCategoryPane[i]);
        }
        fopMsgM_setNowAlphaZero(&m2228);
        fopMsgM_setNowAlphaZero(&m2260);
        fopMsgM_setNowAlphaZero(&m2298);
        fopMsgM_setNowAlphaZero(&m22D0);

        if (mItemState[4] != 3) {
            dComIfGs_setSelectItem(mItemState[4], mItemState[1]);
            dComIfGp_setSelectItem(mItemState[4]);
            mItemState[4] = 3;

            if (mItemState[3] != 3) {
                dComIfGs_setSelectItem(mItemState[3], mItemState[2]);
                dComIfGp_setSelectItem(mItemState[3]);
                mItemState[3] = 3;
            }

            JAIZelBasic::zel_basic->seStart(0x817, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
        }

        if (dMeter_subWinFlag() != 0) {
            subWindowDelete();
        }
    }

    return ret;
}

/* 801D1CD4-801D21A0       .text _open2__12dMenu_Item_cFv */
bool dMenu_Item_c::_open2() {
    /* Nonmatching */
    s16 x = g_miHIO.mMainSlideX;
    s16 v = g_menuHIO.field_0x92;
    bool ret = false;
    if (mTimer == 0) {
        for (int i = 0; i < 2; i++) {
            strcpy(name[i], "");
            strcpy(note[i], "");
            ((J2DTextBox*)(&m890)[i].pane)->setString(name[i]);
        }
        ((J2DTextBox*)m778.pane)->setString(note[0]);
        ((J2DTextBox*)m740.pane)->setString(note[1]);
        itemnameSet();
        if (mNowItem != 0x15 &&
            !(recollectBossCheck() && (dComIfGs_getItem(mNowItem) == dItemNo_WATER_BOTTLE_e || dComIfGs_getItem(mNowItem) == dItemNo_FIREFLY_BOTTLE_e ||
                                       dComIfGs_getItem(mNowItem) == dItemNo_FOREST_WATER_e)))
        {
            itemnoteSet();
            if (dComIfGs_getItem(mNowItem) != dItemNo_NONE_e) {
                dComIfGp_setDoStatusForce(0x21);
            } else {
                dComIfGp_setDoStatusForce(0);
                dComIfGp_setDoStatus(0);
            }
        } else {
            dComIfGp_setDoStatusForce(0x17);
        }
    }
    mTimer = mTimer + 1;
    if (mTimer <= v && mTimer > 0) {
        if (mTriggerInfo == 2) {
            mainOpenProc(mTimer, v, x);
        } else {
            mainOpenProc(mTimer, v, -x);
        }
        titleOpenProc(mTimer, v);
        noteOpenProc(mTimer, v);
        nameOpenProc(mTimer, v);
    }
    if (mTimer >= v) {
        ret = true;
    }
    return ret;
}

/* 801D21A0-801D2A4C       .text _close2__12dMenu_Item_cFv */
bool dMenu_Item_c::_close2() {
    bool ret = false;
    f32 note_ratio;
    mTimer--;
    f32 main_offset_x = g_miHIO.mMainSlideX * fopMsgM_valueIncrease(g_menuHIO.field_0x92, g_menuHIO.field_0x92 - mTimer, 0);
    f32 title_offset_y = g_miHIO.mTitleSlideY * fopMsgM_valueIncrease(g_menuHIO.field_0x92, g_menuHIO.field_0x92 - mTimer, 0);
    f32 name_offset_y = g_miHIO.mNameSlideY * fopMsgM_valueIncrease(g_menuHIO.field_0x92, g_menuHIO.field_0x92 - mTimer, 0);
    note_ratio = fopMsgM_valueIncrease(g_menuHIO.field_0x92, g_menuHIO.field_0x92 - mTimer, 0);
    f32 emitter_alpha_ratio = fopMsgM_valueIncrease(g_menuHIO.field_0x92, mTimer, 0);

    for (int i = 0; i < 2; i++) {
        if (mpEmitter[i] != NULL) {
            mpEmitter[i]->mGlobalPrmColor.a = 255.0f * emitter_alpha_ratio;
        }
    }

    if (mTriggerInfo == 2) {
        mainTrans(-main_offset_x, 0.0f);
        titleTrans(0.0f, title_offset_y);
        noteRotate(dMenu_scale(g_miHIO.mNoteSlideY, note_ratio), dMenu_lerp(m820.mUserArea, g_miHIO.mNoteOpenAngle, note_ratio));
        nameTrans(0.0f, name_offset_y);
    } else if (mTriggerInfo == 1) {
        mainTrans(main_offset_x, 0.0f);
        titleTrans(0.0f, title_offset_y);
        noteRotate(dMenu_scale(g_miHIO.mNoteSlideY, note_ratio), dMenu_lerp(m820.mUserArea, g_miHIO.mNoteOpenAngle, note_ratio));
        nameTrans(0.0f, name_offset_y);
    }

    if (mTimer > 0) {
        m2422 = 1;
    } else {
        ret = true;
        m2422 = 0;

        for (int i = 0; i < 15; i++) {
            fopMsgM_setNowAlphaZero(&m0B0[i]);
        }
        fopMsgM_setNowAlphaZero(&m740);
        fopMsgM_setNowAlphaZero(&m778);
        fopMsgM_setNowAlphaZero(&m7B0);
        fopMsgM_setNowAlphaZero(&m7E8);
        fopMsgM_setNowAlphaZero(&m820);
        fopMsgM_setNowAlphaZero(&mItemNamePane);
        fopMsgM_setNowAlphaZero(&m890);
        fopMsgM_setNowAlphaZero(&m8C8);
        fopMsgM_setNowAlphaZero(&m900);
        fopMsgM_setNowAlphaZero(&m938);
        fopMsgM_setNowAlphaZero(&m970);
        fopMsgM_setNowAlphaZero(&m9A8);
        fopMsgM_setNowAlphaZero(&m9E0);

        for (int i = 0; i < 4; i++) {
            fopMsgM_setNowAlphaZero(&mCursorPane[i]);
        }

        for (int i = 0; i < 8; i++) {
            fopMsgM_setNowAlphaZero(&mSubItemNumOnesPane[i]);
            fopMsgM_setNowAlphaZero(&mSubItemNumTensPane[i]);
            fopMsgM_setNowAlphaZero(&mSubItemPane[i]);
            fopMsgM_setNowAlphaZero(&mSubItemShadowPane[i]);
        }
        fopMsgM_setNowAlphaZero(&mSubItemBackPane);
        fopMsgM_setNowAlphaZero(&mSubItemBackShadowPane);

        for (int i = 0; i < 9; i++) {
            fopMsgM_setNowAlphaZero(&m1268[i]);
        }
        fopMsgM_setNowAlphaZero(&m1460);
        fopMsgM_setNowAlphaZero(&mSaveIconPane);
        fopMsgM_setNowAlphaZero(&m14D0);
        fopMsgM_setNowAlphaZero(&m1508);
        fopMsgM_setNowAlphaZero(&mPictureNumPane);
        fopMsgM_setNowAlphaZero(&mArrowNumOnesPane);
        fopMsgM_setNowAlphaZero(&mArrowNumTensPane);
        fopMsgM_setNowAlphaZero(&mBombNumOnesPane);
        fopMsgM_setNowAlphaZero(&mBombNumTensPane);

        for (int i = 0; i < 0x15; i++) {
            fopMsgM_setNowAlphaZero(&mItemPane[i]);
            fopMsgM_setNowAlphaZero(&mItemShadowPane[i]);
        }

        for (int i = 0; i < 3; i++) {
            fopMsgM_setNowAlphaZero(&mBowGlowPane[i]);
            fopMsgM_setNowAlphaZero(&mCheckMarkPane[i]);
        }

        for (int i = 0; i < 6; i++) {
            fopMsgM_setNowAlphaZero(&mCategoryPane[i]);
        }
        fopMsgM_setNowAlphaZero(&m2228);
        fopMsgM_setNowAlphaZero(&m2260);
        fopMsgM_setNowAlphaZero(&m2298);
        fopMsgM_setNowAlphaZero(&m22D0);

        if (mItemState[4] != 3) {
            dComIfGs_setSelectItem(mItemState[4], mItemState[1]);
            dComIfGp_setSelectItem(mItemState[4]);
            mItemState[4] = 3;

            if (mItemState[3] != 3) {
                dComIfGs_setSelectItem(mItemState[3], mItemState[2]);
                dComIfGp_setSelectItem(mItemState[3]);
                mItemState[3] = 3;
            }

            JAIZelBasic::zel_basic->seStart(0x817, (cXyz*)0x0, 0, 0, 1.0, 1.0, -1.0, -1.0, 0);
        }

        if (dMeter_subWinFlag() != 0) {
            subWindowDelete();
        }
    }

    return ret;
}

/* 801D2A4C-801D2AB8       .text __dt__12dMenu_Item_cFv */
dMenu_Item_c::~dMenu_Item_c() {}

/* 801D2AB8-801D2AE4       .text draw__12dMenu_Item_cFv */
void dMenu_Item_c::draw() {
    _draw();
}
